USE final;

/* ==========================================
   AUCTION 100건 + BID 1~2건 더미 데이터
   - 기존 컬럼만 사용 (신규 컬럼/테이블 없음)
   - 모든 FK는 서브쿼리로 참조하여 PK 하드코딩(할루시네이션) 방지


    작동안하는 쓰레기 수정 필요
   ========================================== */

-- 카테고리 3(보호대), 4(의류/신발)에 해당하는 item이 기존 더미에 없어 입찰용으로 추가
INSERT INTO item (item_name, item_category_idx, item_brand, item_condition, item_thumbnail_img, item_detail_img, item_is_deleted) VALUES
                                                                                                                                      ('무릎 보호대 세트 - 사용감 적음', 3, 'McDavid', 'USED_A', NULL, NULL, 'N'),
                                                                                                                                      ('손목/팔꿈치 보호대 세트', 3, 'NoBrand', 'USED_B', NULL, NULL, 'N'),
                                                                                                                                      ('헬스용 손목 스트랩 + 무릎 슬리브', 3, 'Rehband', 'USED_A', NULL, NULL, 'N'),
                                                                                                                                      ('축구용 정강이 보호대 (스타킹 포함)', 3, 'Nike', 'NEW', NULL, NULL, 'N'),
                                                                                                                                      ('기능성 운동 레깅스 (블랙)', 4, 'Lululemon', 'USED_A', NULL, NULL, 'N'),
                                                                                                                                      ('드라이핏 라운드 티셔츠 세트', 4, 'Nike', 'NEW', NULL, NULL, 'N'),
                                                                                                                                      ('방수 자켓 - 등산/캠핑용', 4, 'NorthFace', 'USED_B', NULL, NULL, 'N'),
                                                                                                                                      ('골프웨어 상하의 세트', 4, 'Callaway', 'USED_A', NULL, NULL, 'N');

-- AUCTION 100건
INSERT INTO auction (
    buyer_idx, item_category_idx, auction_thumbnail_img,
    auction_title, auction_desc, auction_target_price, auction_view_count,
    auction_start_at, auction_end_at, auction_decision_deadline,
    auction_status_idx, auction_regdate, auction_moddate,
    auction_is_deleted, auction_deldate
) VALUES
      (4, 1, 'https://loremflickr.com/600/400/soccer-ball?lock=1',
       '초보자용 공인구 어떤 거 사야 할까요 (DUMMY-001)', '이제 막 시작한 초보입니다. 입문용으로 적당한 공인구 제안 부탁드립니다.', 110000, 41,
       NOW() - INTERVAL 3 DAY, NOW() + INTERVAL 6 DAY, NOW() + INTERVAL 8 DAY,
       1, NOW() - INTERVAL 3 DAY, NULL,
       'N', NULL),
      (3, 2, 'https://loremflickr.com/600/400/tennis-racket?lock=2',
       '연습용 아이언 세트 저렴하게 넘겨주실 분 (DUMMY-002)', '연습용이라 흠집 있어도 괜찮습니다. 가격 위주로 제안 부탁드려요.', 770000, 15,
       NOW() - INTERVAL 4 DAY, NOW() + INTERVAL 5 DAY, NOW() + INTERVAL 7 DAY,
       1, NOW() - INTERVAL 4 DAY, NULL,
       'N', NULL),
      (10, 3, 'https://loremflickr.com/600/400/sports-protector?lock=3',
       '새 제품 보호장비 세트 저렴하게 구합니다 (DUMMY-003)', '위생 때문에 가급적 새 제품 보호장비 세트으로 찾고 있어요.', 50000, 25,
       NOW() - INTERVAL 17 DAY, NOW() - INTERVAL 13 DAY, NOW() - INTERVAL 10 DAY,
       5, NOW() - INTERVAL 17 DAY, NOW() - INTERVAL 13 DAY,
       'N', NULL),
      (1, 4, 'https://loremflickr.com/600/400/sportswear?lock=4',
       '운동용 레깅스 사이즈 맞는 거 구해요 (DUMMY-004)', '평소 운동할 때 입을 레깅스 찾고 있습니다. 신축성 좋은 제품이면 좋겠어요.', 60000, 55,
       NOW() - INTERVAL 1 DAY, NOW() + INTERVAL 6 DAY, NOW() + INTERVAL 7 DAY,
       1, NOW() - INTERVAL 1 DAY, NULL,
       'N', NULL),
      (7, 5, 'https://loremflickr.com/600/400/dumbbell?lock=5',
       '홈트용 홈트 용품 구합니다 (DUMMY-005)', '집에서 운동할 때 쓸 홈트 용품 찾고 있어요. 부피 너무 크지 않은 제품이면 좋겠습니다.', 270000, 24,
       NOW() - INTERVAL 24 DAY, NOW() - INTERVAL 19 DAY, NOW() - INTERVAL 16 DAY,
       3, NOW() - INTERVAL 24 DAY, NOW() - INTERVAL 19 DAY,
       'N', NULL),
      (9, 6, 'https://loremflickr.com/600/400/outdoor-gear?lock=6',
       '텐트 풀세트로 구합니다 (DUMMY-006)', '시즌 시작 전에 텐트 풀세트 장만하려고 합니다. 사용감 있어도 괜찮아요.', 370000, 48,
       NOW() - INTERVAL 10 DAY, NOW() - INTERVAL 1 DAY, NOW() + INTERVAL 1 DAY,
       2, NOW() - INTERVAL 10 DAY, NULL,
       'N', NULL),
      (3, 7, 'https://loremflickr.com/600/400/swimming-pool?lock=7',
       '가성비 수영복 구성으로 구합니다 (DUMMY-007)', '예산 맞춰서 무난한 수영복 구성으로 제안 부탁드려요.', 50000, 29,
       NOW() - INTERVAL 2 DAY, NOW() + INTERVAL 5 DAY, NOW() + INTERVAL 6 DAY,
       1, NOW() - INTERVAL 2 DAY, NULL,
       'N', NULL),
      (5, 8, 'https://loremflickr.com/600/400/backpack?lock=8',
       '스포츠 잡화 상태 좋은 거 구합니다 (DUMMY-008)', '평소 쓸 스포츠 잡화 찾고 있어요. 사용감 적은 제품으로 제안 부탁드립니다.', 100000, 53,
       NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 9 DAY, NOW() - INTERVAL 8 DAY,
       3, NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 9 DAY,
       'N', NULL),
      (10, 1, 'https://loremflickr.com/600/400/volleyball?lock=9',
       '연습용 공용 공인구 상태 좋은 거 구합니다 (DUMMY-009)', '연습용 공 동호회에서 쓸 공 찾고 있어요. 사용감 적고 바람 빠짐 없는 제품이면 좋겠습니다.', 110000, 20,
       NOW(), NOW() + INTERVAL 1 DAY, NOW() + INTERVAL 3 DAY,
       1, NOW(), NULL,
       'N', NULL),
      (1, 2, 'https://loremflickr.com/600/400/golf-club?lock=10',
       '입문용 드라이버 가성비 좋은 걸로 구해요 (DUMMY-010)', '예산 맞춰서 입문용 드라이버 구성으로 제안해주시면 감사하겠습니다.', 860000, 15,
       NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 9 DAY, NOW() - INTERVAL 6 DAY,
       3, NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 9 DAY,
       'N', NULL),
      (9, 3, 'https://loremflickr.com/600/400/elbow-pad?lock=11',
       '손목 보호대 사이즈 맞는 걸로 구합니다 (DUMMY-011)', '운동 중 부상 방지용 손목 보호대 찾고 있어요. 사이즈 잘 맞는 제품이면 좋겠습니다.', 40000, 49,
       NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 8 DAY, NOW() - INTERVAL 5 DAY,
       3, NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 8 DAY,
       'N', NULL),
      (9, 4, 'https://loremflickr.com/600/400/sports-jacket?lock=12',
       '가성비 운동복 구성으로 구합니다 (DUMMY-012)', '여러 벌 필요해서 가성비 좋은 운동복 구성으로 제안 부탁드려요.', 140000, 55,
       NOW() - INTERVAL 3 DAY, NOW() + INTERVAL 2 DAY, NOW() + INTERVAL 5 DAY,
       1, NOW() - INTERVAL 3 DAY, NULL,
       'N', NULL),
      (7, 5, 'https://loremflickr.com/600/400/gym?lock=13',
       '입문용 아령 세트 가격대 맞춰 구해요 (DUMMY-013)', '운동 입문이라 너무 비싸지 않은 아령 세트으로 제안 부탁드립니다.', 280000, 42,
       NOW() - INTERVAL 21 DAY, NOW() - INTERVAL 15 DAY, NOW() - INTERVAL 12 DAY,
       3, NOW() - INTERVAL 21 DAY, NOW() - INTERVAL 15 DAY,
       'N', NULL),
      (4, 6, 'https://loremflickr.com/600/400/ski-equipment?lock=14',
       '캠핑 의자 풀세트로 구합니다 (DUMMY-014)', '시즌 시작 전에 캠핑 의자 풀세트 장만하려고 합니다. 사용감 있어도 괜찮아요.', 240000, 14,
       NOW() - INTERVAL 20 DAY, NOW() - INTERVAL 17 DAY, NOW() - INTERVAL 14 DAY,
       3, NOW() - INTERVAL 20 DAY, NOW() - INTERVAL 17 DAY,
       'N', NULL),
      (10, 7, 'https://loremflickr.com/600/400/swimsuit?lock=15',
       '입문용 수모 세트 추천 부탁드려요 (DUMMY-015)', '수영 처음 시작하는데 어떤 수모 세트 사야 할지 모르겠어요. 제안 부탁드립니다.', 50000, 14,
       NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 9 DAY, NOW() - INTERVAL 8 DAY,
       3, NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 9 DAY,
       'N', NULL),
      (6, 8, 'https://loremflickr.com/600/400/sports-bag?lock=16',
       '백팩 상태 좋은 거 구합니다 (DUMMY-016)', '평소 쓸 백팩 찾고 있어요. 사용감 적은 제품으로 제안 부탁드립니다.', 110000, 4,
       NOW() - INTERVAL 7 DAY, NOW() - INTERVAL 2 DAY, NOW() + INTERVAL 2 DAY,
       2, NOW() - INTERVAL 7 DAY, NULL,
       'N', NULL),
      (10, 1, 'https://loremflickr.com/600/400/basketball?lock=17',
       '실내 연습용 공인구 추천 부탁드려요 (DUMMY-017)', '집/체육관에서 가볍게 연습할 공인구 찾습니다. 너무 무겁지 않은 사이즈로 부탁드려요.', 110000, 36,
       NOW() - INTERVAL 6 DAY, NOW() - INTERVAL 1 DAY, NOW() + INTERVAL 2 DAY,
       2, NOW() - INTERVAL 6 DAY, NULL,
       'N', NULL),
      (2, 2, 'https://loremflickr.com/600/400/baseball-bat?lock=18',
       '아이언 세트 중급자용으로 제안 부탁드려요 (DUMMY-018)', '핸디/실력 중급 정도입니다. 무난하게 쓸 수 있는 아이언 세트 찾고 있어요.', 570000, 42,
       NOW() - INTERVAL 21 DAY, NOW() - INTERVAL 15 DAY, NOW() - INTERVAL 13 DAY,
       5, NOW() - INTERVAL 21 DAY, NOW() - INTERVAL 15 DAY,
       'N', NULL),
      (2, 3, 'https://loremflickr.com/600/400/knee-brace?lock=19',
       '손목 보호대 사이즈 맞는 걸로 구합니다 (DUMMY-019)', '운동 중 부상 방지용 손목 보호대 찾고 있어요. 사이즈 잘 맞는 제품이면 좋겠습니다.', 60000, 3,
       NOW() - INTERVAL 20 DAY, NOW() - INTERVAL 17 DAY, NOW() - INTERVAL 16 DAY,
       3, NOW() - INTERVAL 20 DAY, NOW() - INTERVAL 17 DAY,
       'N', NULL),
      (9, 4, 'https://loremflickr.com/600/400/running-shoes?lock=20',
       '계절용 운동복 추천 부탁드립니다 (DUMMY-020)', '날씨에 맞춰 입을 운동복 찾고 있어요. 브랜드는 크게 상관없습니다.', 70000, 28,
       NOW() - INTERVAL 3 DAY, NOW() + INTERVAL 2 DAY, NOW() + INTERVAL 4 DAY,
       1, NOW() - INTERVAL 3 DAY, NULL,
       'N', NULL),
      (2, 5, 'https://loremflickr.com/600/400/yoga-mat?lock=21',
       '헬스장에서 쓸 홈트 용품 추천받습니다 (DUMMY-021)', '헬스장 다닐 때 들고 다닐 홈트 용품 입니다. 가벼우면서 튼튼한 제품 부탁드려요.', 250000, 28,
       NOW(), NOW() + INTERVAL 1 DAY, NOW() + INTERVAL 4 DAY,
       1, NOW(), NULL,
       'N', NULL),
      (2, 6, 'https://loremflickr.com/600/400/camping-tent?lock=22',
       '스키 장비 풀세트로 구합니다 (DUMMY-022)', '시즌 시작 전에 스키 장비 풀세트 장만하려고 합니다. 사용감 있어도 괜찮아요.', 680000, 59,
       NOW() - INTERVAL 1 DAY, NOW() + INTERVAL 2 DAY, NOW() + INTERVAL 4 DAY,
       1, NOW() - INTERVAL 1 DAY, NULL,
       'N', NULL),
      (4, 7, 'https://loremflickr.com/600/400/swim-goggles?lock=23',
       '가성비 수영복 구성으로 구합니다 (DUMMY-023)', '예산 맞춰서 무난한 수영복 구성으로 제안 부탁드려요.', 110000, 55,
       NOW(), NOW() + INTERVAL 2 DAY, NOW() + INTERVAL 4 DAY,
       1, NOW(), NULL,
       'N', NULL),
      (5, 8, 'https://loremflickr.com/600/400/sports-gloves?lock=24',
       '새 제품 백팩 깨끗한 걸로 구해요 (DUMMY-024)', '거의 새 제품 수준의 백팩 찾고 있습니다.', 180000, 59,
       NOW() - INTERVAL 19 DAY, NOW() - INTERVAL 13 DAY, NOW() - INTERVAL 10 DAY,
       6, NOW() - INTERVAL 19 DAY, NOW() - INTERVAL 13 DAY,
       'Y', NOW() - INTERVAL 13 DAY),
      (3, 1, 'https://loremflickr.com/600/400/soccer-ball?lock=25',
       '시합용 연습용 공 새 제품으로 구해요 (DUMMY-025)', '동호회 시합에 쓸 공인구라 상태 깨끗한 제품으로 부탁드립니다.', 80000, 12,
       NOW() - INTERVAL 16 DAY, NOW() - INTERVAL 13 DAY, NOW() - INTERVAL 10 DAY,
       4, NOW() - INTERVAL 16 DAY, NOW() - INTERVAL 13 DAY,
       'N', NULL),
      (6, 2, 'https://loremflickr.com/600/400/tennis-racket?lock=26',
       '라켓/클럽 중급자용으로 제안 부탁드려요 (DUMMY-026)', '핸디/실력 중급 정도입니다. 무난하게 쓸 수 있는 라켓/클럽 찾고 있어요.', 330000, 3,
       NOW() - INTERVAL 9 DAY, NOW() - INTERVAL 1 DAY, NOW() + INTERVAL 3 DAY,
       2, NOW() - INTERVAL 9 DAY, NULL,
       'N', NULL),
      (1, 3, 'https://loremflickr.com/600/400/sports-protector?lock=27',
       '재활용 보호장비 세트 상태 좋은 거 구해요 (DUMMY-027)', '최근 부상이 있어서 재활할 때 쓸 보호장비 세트 제안 부탁드립니다.', 30000, 32,
       NOW() - INTERVAL 15 DAY, NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 9 DAY,
       4, NOW() - INTERVAL 15 DAY, NOW() - INTERVAL 12 DAY,
       'N', NULL),
      (7, 4, 'https://loremflickr.com/600/400/sportswear?lock=28',
       '계절용 운동복 추천 부탁드립니다 (DUMMY-028)', '날씨에 맞춰 입을 운동복 찾고 있어요. 브랜드는 크게 상관없습니다.', 190000, 7,
       NOW() - INTERVAL 4 DAY, NOW() + INTERVAL 2 DAY, NOW() + INTERVAL 5 DAY,
       1, NOW() - INTERVAL 4 DAY, NULL,
       'N', NULL),
      (7, 5, 'https://loremflickr.com/600/400/dumbbell?lock=29',
       '홈트용 러닝화 구합니다 (DUMMY-029)', '집에서 운동할 때 쓸 러닝화 찾고 있어요. 부피 너무 크지 않은 제품이면 좋겠습니다.', 260000, 42,
       NOW() - INTERVAL 20 DAY, NOW() - INTERVAL 15 DAY, NOW() - INTERVAL 14 DAY,
       4, NOW() - INTERVAL 20 DAY, NOW() - INTERVAL 15 DAY,
       'N', NULL),
      (4, 6, 'https://loremflickr.com/600/400/outdoor-gear?lock=30',
       '중고 스키 장비 상태 좋은 거 구해요 (DUMMY-030)', '예산 절약하려고 중고 스키 장비 찾고 있습니다. 보관 상태 좋은 제품이면 좋겠어요.', 450000, 16,
       NOW() - INTERVAL 1 DAY, NOW() + INTERVAL 6 DAY, NOW() + INTERVAL 9 DAY,
       1, NOW() - INTERVAL 1 DAY, NULL,
       'N', NULL),
      (6, 7, 'https://loremflickr.com/600/400/swimming-pool?lock=31',
       '가성비 수영복 구성으로 구합니다 (DUMMY-031)', '예산 맞춰서 무난한 수영복 구성으로 제안 부탁드려요.', 170000, 59,
       NOW(), NOW() + INTERVAL 1 DAY, NOW() + INTERVAL 3 DAY,
       1, NOW(), NULL,
       'N', NULL),
      (2, 8, 'https://loremflickr.com/600/400/backpack?lock=32',
       '스포츠 잡화 상태 좋은 거 구합니다 (DUMMY-032)', '평소 쓸 스포츠 잡화 찾고 있어요. 사용감 적은 제품으로 제안 부탁드립니다.', 100000, 34,
       NOW() - INTERVAL 9 DAY, NOW() - INTERVAL 1 DAY, NOW() + INTERVAL 1 DAY,
       2, NOW() - INTERVAL 9 DAY, NULL,
       'N', NULL),
      (4, 1, 'https://loremflickr.com/600/400/volleyball?lock=33',
       '시합용 공용 공인구 상태 좋은 거 구합니다 (DUMMY-033)', '시합용 공 동호회에서 쓸 공 찾고 있어요. 사용감 적고 바람 빠짐 없는 제품이면 좋겠습니다.', 80000, 23,
       NOW() - INTERVAL 15 DAY, NOW() - INTERVAL 9 DAY, NOW() - INTERVAL 6 DAY,
       3, NOW() - INTERVAL 15 DAY, NOW() - INTERVAL 9 DAY,
       'N', NULL),
      (10, 2, 'https://loremflickr.com/600/400/golf-club?lock=34',
       '연습용 라켓/클럽 저렴하게 넘겨주실 분 (DUMMY-034)', '연습용이라 흠집 있어도 괜찮습니다. 가격 위주로 제안 부탁드려요.', 710000, 51,
       NOW() - INTERVAL 10 DAY, NOW() - INTERVAL 5 DAY, NOW() - INTERVAL 2 DAY,
       3, NOW() - INTERVAL 10 DAY, NOW() - INTERVAL 5 DAY,
       'N', NULL),
      (5, 3, 'https://loremflickr.com/600/400/elbow-pad?lock=35',
       '재활용 무릎 보호대 상태 좋은 거 구해요 (DUMMY-035)', '최근 부상이 있어서 재활할 때 쓸 무릎 보호대 제안 부탁드립니다.', 30000, 7,
       NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 9 DAY, NOW() - INTERVAL 7 DAY,
       3, NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 9 DAY,
       'N', NULL),
      (6, 4, 'https://loremflickr.com/600/400/sports-jacket?lock=36',
       '계절용 기능성 의류 추천 부탁드립니다 (DUMMY-036)', '날씨에 맞춰 입을 기능성 의류 찾고 있어요. 브랜드는 크게 상관없습니다.', 150000, 13,
       NOW() - INTERVAL 2 DAY, NOW() + INTERVAL 5 DAY, NOW() + INTERVAL 7 DAY,
       1, NOW() - INTERVAL 2 DAY, NULL,
       'N', NULL),
      (2, 5, 'https://loremflickr.com/600/400/gym?lock=37',
       '홈트용 요가 매트 구합니다 (DUMMY-037)', '집에서 운동할 때 쓸 요가 매트 찾고 있어요. 부피 너무 크지 않은 제품이면 좋겠습니다.', 210000, 40,
       NOW() - INTERVAL 18 DAY, NOW() - INTERVAL 15 DAY, NOW() - INTERVAL 14 DAY,
       6, NOW() - INTERVAL 18 DAY, NOW() - INTERVAL 15 DAY,
       'Y', NOW() - INTERVAL 15 DAY),
      (5, 6, 'https://loremflickr.com/600/400/ski-equipment?lock=38',
       '초보자용 캠핑 의자 추천 부탁드려요 (DUMMY-038)', '아웃도어 입문이라 어떤 캠핑 의자 사야 할지 모르겠어요. 추천 및 제안 부탁드립니다.', 670000, 10,
       NOW() - INTERVAL 8 DAY, NOW() - INTERVAL 2 DAY, NOW() + INTERVAL 3 DAY,
       2, NOW() - INTERVAL 8 DAY, NULL,
       'N', NULL),
      (2, 7, 'https://loremflickr.com/600/400/swimsuit?lock=39',
       '수영 수영복 구합니다 (DUMMY-039)', '수영장 다닐 때 쓸 수영복 찾고 있어요. 사이즈/색상 협의 가능합니다.', 190000, 4,
       NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 11 DAY, NOW() - INTERVAL 9 DAY,
       4, NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 11 DAY,
       'N', NULL),
      (7, 8, 'https://loremflickr.com/600/400/sports-bag?lock=40',
       '선물용 스포츠 잡화 추천 부탁드려요 (DUMMY-040)', '지인 선물용으로 쓸 스포츠 잡화 입니다. 포장 상태 좋은 제품이면 좋겠어요.', 50000, 8,
       NOW() - INTERVAL 2 DAY, NOW() + INTERVAL 3 DAY, NOW() + INTERVAL 4 DAY,
       1, NOW() - INTERVAL 2 DAY, NULL,
       'N', NULL),
      (4, 1, 'https://loremflickr.com/600/400/basketball?lock=41',
       '실내 연습용 시합용 공 추천 부탁드려요 (DUMMY-041)', '집/체육관에서 가볍게 연습할 시합용 공 찾습니다. 너무 무겁지 않은 사이즈로 부탁드려요.', 50000, 42,
       NOW() - INTERVAL 2 DAY, NOW() + INTERVAL 7 DAY, NOW() + INTERVAL 10 DAY,
       1, NOW() - INTERVAL 2 DAY, NULL,
       'N', NULL),
      (4, 2, 'https://loremflickr.com/600/400/baseball-bat?lock=42',
       '입문용 드라이버 가성비 좋은 걸로 구해요 (DUMMY-042)', '예산 맞춰서 입문용 드라이버 구성으로 제안해주시면 감사하겠습니다.', 400000, 55,
       NOW() - INTERVAL 1 DAY, NOW() + INTERVAL 4 DAY, NOW() + INTERVAL 5 DAY,
       1, NOW() - INTERVAL 1 DAY, NULL,
       'N', NULL),
      (7, 3, 'https://loremflickr.com/600/400/knee-brace?lock=43',
       '운동 시 착용할 무릎 보호대 추천받습니다 (DUMMY-043)', '관절 보호 목적으로 착용할 무릎 보호대 추천 및 제안 부탁드립니다.', 80000, 51,
       NOW() - INTERVAL 1 DAY, NOW() + INTERVAL 3 DAY, NOW() + INTERVAL 4 DAY,
       1, NOW() - INTERVAL 1 DAY, NULL,
       'N', NULL),
      (7, 4, 'https://loremflickr.com/600/400/running-shoes?lock=44',
       '운동용 기능성 의류 사이즈 맞는 거 구해요 (DUMMY-044)', '평소 운동할 때 입을 기능성 의류 찾고 있습니다. 신축성 좋은 제품이면 좋겠어요.', 50000, 55,
       NOW() - INTERVAL 3 DAY, NOW() + INTERVAL 2 DAY, NOW() + INTERVAL 3 DAY,
       1, NOW() - INTERVAL 3 DAY, NULL,
       'N', NULL),
      (5, 5, 'https://loremflickr.com/600/400/yoga-mat?lock=45',
       '입문용 홈트 용품 가격대 맞춰 구해요 (DUMMY-045)', '운동 입문이라 너무 비싸지 않은 홈트 용품으로 제안 부탁드립니다.', 150000, 52,
       NOW() - INTERVAL 1 DAY, NOW() + INTERVAL 1 DAY, NOW() + INTERVAL 4 DAY,
       1, NOW() - INTERVAL 1 DAY, NULL,
       'N', NULL),
      (6, 6, 'https://loremflickr.com/600/400/camping-tent?lock=46',
       '가족용 텐트 여러 개 구합니다 (DUMMY-046)', '가족이 다 같이 쓸 텐트 여러 세트 필요합니다.', 240000, 17,
       NOW() - INTERVAL 18 DAY, NOW() - INTERVAL 13 DAY, NOW() - INTERVAL 10 DAY,
       3, NOW() - INTERVAL 18 DAY, NOW() - INTERVAL 13 DAY,
       'N', NULL),
      (9, 7, 'https://loremflickr.com/600/400/swim-goggles?lock=47',
       '가성비 수모 세트 구성으로 구합니다 (DUMMY-047)', '예산 맞춰서 무난한 수모 세트 구성으로 제안 부탁드려요.', 50000, 21,
       NOW() - INTERVAL 13 DAY, NOW() - INTERVAL 8 DAY, NOW() - INTERVAL 7 DAY,
       3, NOW() - INTERVAL 13 DAY, NOW() - INTERVAL 8 DAY,
       'N', NULL),
      (1, 8, 'https://loremflickr.com/600/400/sports-gloves?lock=48',
       '가성비 스포츠 잡화 구합니다 (DUMMY-048)', '예산 맞춰서 가성비 좋은 스포츠 잡화으로 제안 부탁드려요.', 170000, 6,
       NOW() - INTERVAL 21 DAY, NOW() - INTERVAL 16 DAY, NOW() - INTERVAL 14 DAY,
       3, NOW() - INTERVAL 21 DAY, NOW() - INTERVAL 16 DAY,
       'N', NULL),
      (7, 1, 'https://loremflickr.com/600/400/soccer-ball?lock=49',
       '연습용 공용 공인구 상태 좋은 거 구합니다 (DUMMY-049)', '연습용 공 동호회에서 쓸 공 찾고 있어요. 사용감 적고 바람 빠짐 없는 제품이면 좋겠습니다.', 130000, 57,
       NOW() - INTERVAL 1 DAY, NOW() + INTERVAL 3 DAY, NOW() + INTERVAL 4 DAY,
       1, NOW() - INTERVAL 1 DAY, NULL,
       'N', NULL),
      (1, 2, 'https://loremflickr.com/600/400/tennis-racket?lock=50',
       '피팅 포함 라켓/클럽 구합니다 (DUMMY-050)', '제 체형에 맞는 피팅값으로 조정 가능한 라켓/클럽 찾고 있습니다.', 890000, 33,
       NOW() - INTERVAL 4 DAY, NOW() + INTERVAL 6 DAY, NOW() + INTERVAL 9 DAY,
       1, NOW() - INTERVAL 4 DAY, NULL,
       'N', NULL),
      (6, 3, 'https://loremflickr.com/600/400/sports-protector?lock=51',
       '재활용 보호장비 세트 상태 좋은 거 구해요 (DUMMY-051)', '최근 부상이 있어서 재활할 때 쓸 보호장비 세트 제안 부탁드립니다.', 30000, 27,
       NOW() - INTERVAL 20 DAY, NOW() - INTERVAL 15 DAY, NOW() - INTERVAL 12 DAY,
       6, NOW() - INTERVAL 20 DAY, NOW() - INTERVAL 15 DAY,
       'Y', NOW() - INTERVAL 15 DAY),
      (9, 4, 'https://loremflickr.com/600/400/sportswear?lock=52',
       '가성비 운동복 구성으로 구합니다 (DUMMY-052)', '여러 벌 필요해서 가성비 좋은 운동복 구성으로 제안 부탁드려요.', 150000, 19,
       NOW() - INTERVAL 8 DAY, NOW() - INTERVAL 1 DAY, NOW() + INTERVAL 2 DAY,
       2, NOW() - INTERVAL 8 DAY, NULL,
       'N', NULL),
      (4, 5, 'https://loremflickr.com/600/400/dumbbell?lock=53',
       '헬스장에서 쓸 요가 매트 추천받습니다 (DUMMY-053)', '헬스장 다닐 때 들고 다닐 요가 매트 입니다. 가벼우면서 튼튼한 제품 부탁드려요.', 290000, 26,
       NOW() - INTERVAL 3 DAY, NOW() + INTERVAL 6 DAY, NOW() + INTERVAL 9 DAY,
       1, NOW() - INTERVAL 3 DAY, NULL,
       'N', NULL),
      (7, 6, 'https://loremflickr.com/600/400/outdoor-gear?lock=54',
       '중고 텐트 상태 좋은 거 구해요 (DUMMY-054)', '예산 절약하려고 중고 텐트 찾고 있습니다. 보관 상태 좋은 제품이면 좋겠어요.', 200000, 35,
       NOW() - INTERVAL 7 DAY, NOW() - INTERVAL 1 DAY, NOW() + INTERVAL 1 DAY,
       2, NOW() - INTERVAL 7 DAY, NULL,
       'N', NULL),
      (8, 7, 'https://loremflickr.com/600/400/swimming-pool?lock=55',
       '대회용 수영복 상태 좋은 거 구해요 (DUMMY-055)', '대회 나갈 일이 있어서 상태 좋은 수영복 찾고 있습니다.', 120000, 28,
       NOW() - INTERVAL 1 DAY, NOW() + INTERVAL 5 DAY, NOW() + INTERVAL 7 DAY,
       1, NOW() - INTERVAL 1 DAY, NULL,
       'N', NULL),
      (2, 8, 'https://loremflickr.com/600/400/backpack?lock=56',
       '선물용 스포츠 잡화 추천 부탁드려요 (DUMMY-056)', '지인 선물용으로 쓸 스포츠 잡화 입니다. 포장 상태 좋은 제품이면 좋겠어요.', 140000, 18,
       NOW(), NOW() + INTERVAL 7 DAY, NOW() + INTERVAL 8 DAY,
       1, NOW(), NULL,
       'N', NULL),
      (4, 1, 'https://loremflickr.com/600/400/volleyball?lock=57',
       '초보자용 연습용 공 어떤 거 사야 할까요 (DUMMY-057)', '이제 막 시작한 초보입니다. 입문용으로 적당한 연습용 공 제안 부탁드립니다.', 70000, 51,
       NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 11 DAY, NOW() - INTERVAL 10 DAY,
       3, NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 11 DAY,
       'N', NULL),
      (10, 2, 'https://loremflickr.com/600/400/golf-club?lock=58',
       '피팅 포함 아이언 세트 구합니다 (DUMMY-058)', '제 체형에 맞는 피팅값으로 조정 가능한 아이언 세트 찾고 있습니다.', 790000, 54,
       NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 6 DAY, NOW() - INTERVAL 4 DAY,
       3, NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 6 DAY,
       'N', NULL),
      (7, 3, 'https://loremflickr.com/600/400/elbow-pad?lock=59',
       '재활용 보호장비 세트 상태 좋은 거 구해요 (DUMMY-059)', '최근 부상이 있어서 재활할 때 쓸 보호장비 세트 제안 부탁드립니다.', 60000, 31,
       NOW() - INTERVAL 1 DAY, NOW() + INTERVAL 2 DAY, NOW() + INTERVAL 5 DAY,
       1, NOW() - INTERVAL 1 DAY, NULL,
       'N', NULL),
      (2, 4, 'https://loremflickr.com/600/400/sports-jacket?lock=60',
       '운동용 기능성 의류 사이즈 맞는 거 구해요 (DUMMY-060)', '평소 운동할 때 입을 기능성 의류 찾고 있습니다. 신축성 좋은 제품이면 좋겠어요.', 110000, 49,
       NOW() - INTERVAL 17 DAY, NOW() - INTERVAL 13 DAY, NOW() - INTERVAL 10 DAY,
       3, NOW() - INTERVAL 17 DAY, NOW() - INTERVAL 13 DAY,
       'N', NULL),
      (9, 5, 'https://loremflickr.com/600/400/gym?lock=61',
       '홈트용 홈트 용품 구합니다 (DUMMY-061)', '집에서 운동할 때 쓸 홈트 용품 찾고 있어요. 부피 너무 크지 않은 제품이면 좋겠습니다.', 110000, 15,
       NOW() - INTERVAL 3 DAY, NOW() + INTERVAL 2 DAY, NOW() + INTERVAL 4 DAY,
       1, NOW() - INTERVAL 3 DAY, NULL,
       'N', NULL),
      (8, 6, 'https://loremflickr.com/600/400/ski-equipment?lock=62',
       '중고 스키 장비 상태 좋은 거 구해요 (DUMMY-062)', '예산 절약하려고 중고 스키 장비 찾고 있습니다. 보관 상태 좋은 제품이면 좋겠어요.', 660000, 39,
       NOW() - INTERVAL 4 DAY, NOW() + INTERVAL 4 DAY, NOW() + INTERVAL 7 DAY,
       1, NOW() - INTERVAL 4 DAY, NULL,
       'N', NULL),
      (8, 7, 'https://loremflickr.com/600/400/swimsuit?lock=63',
       '입문용 수영복 추천 부탁드려요 (DUMMY-063)', '수영 처음 시작하는데 어떤 수영복 사야 할지 모르겠어요. 제안 부탁드립니다.', 90000, 28,
       NOW() - INTERVAL 1 DAY, NOW() + INTERVAL 7 DAY, NOW() + INTERVAL 10 DAY,
       1, NOW() - INTERVAL 1 DAY, NULL,
       'N', NULL),
      (4, 8, 'https://loremflickr.com/600/400/sports-bag?lock=64',
       '새 제품 장갑 깨끗한 걸로 구해요 (DUMMY-064)', '거의 새 제품 수준의 장갑 찾고 있습니다.', 180000, 17,
       NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 7 DAY, NOW() - INTERVAL 6 DAY,
       3, NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 7 DAY,
       'N', NULL),
      (6, 1, 'https://loremflickr.com/600/400/basketball?lock=65',
       '초보자용 시합용 공 어떤 거 사야 할까요 (DUMMY-065)', '이제 막 시작한 초보입니다. 입문용으로 적당한 시합용 공 제안 부탁드립니다.', 120000, 57,
       NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 8 DAY, NOW() - INTERVAL 7 DAY,
       4, NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 8 DAY,
       'N', NULL),
      (3, 2, 'https://loremflickr.com/600/400/baseball-bat?lock=66',
       '피팅 포함 아이언 세트 구합니다 (DUMMY-066)', '제 체형에 맞는 피팅값으로 조정 가능한 아이언 세트 찾고 있습니다.', 430000, 45,
       NOW(), NOW() + INTERVAL 4 DAY, NOW() + INTERVAL 6 DAY,
       1, NOW(), NULL,
       'N', NULL),
      (7, 3, 'https://loremflickr.com/600/400/knee-brace?lock=67',
       '새 제품 손목 보호대 저렴하게 구합니다 (DUMMY-067)', '위생 때문에 가급적 새 제품 손목 보호대으로 찾고 있어요.', 40000, 3,
       NOW() - INTERVAL 23 DAY, NOW() - INTERVAL 17 DAY, NOW() - INTERVAL 14 DAY,
       3, NOW() - INTERVAL 23 DAY, NOW() - INTERVAL 17 DAY,
       'N', NULL),
      (10, 4, 'https://loremflickr.com/600/400/running-shoes?lock=68',
       '운동용 기능성 의류 사이즈 맞는 거 구해요 (DUMMY-068)', '평소 운동할 때 입을 기능성 의류 찾고 있습니다. 신축성 좋은 제품이면 좋겠어요.', 120000, 24,
       NOW(), NOW() + INTERVAL 3 DAY, NOW() + INTERVAL 5 DAY,
       1, NOW(), NULL,
       'N', NULL),
      (9, 5, 'https://loremflickr.com/600/400/yoga-mat?lock=69',
       '쿠션 좋은 홈트 용품 찾고 있어요 (DUMMY-069)', '관절 부담 줄이고 싶어서 쿠션감 좋은 홈트 용품 찾습니다.', 250000, 47,
       NOW() - INTERVAL 17 DAY, NOW() - INTERVAL 11 DAY, NOW() - INTERVAL 10 DAY,
       5, NOW() - INTERVAL 17 DAY, NOW() - INTERVAL 11 DAY,
       'N', NULL),
      (8, 6, 'https://loremflickr.com/600/400/camping-tent?lock=70',
       '가족용 캠핑 의자 여러 개 구합니다 (DUMMY-070)', '가족이 다 같이 쓸 캠핑 의자 여러 세트 필요합니다.', 440000, 1,
       NOW() - INTERVAL 2 DAY, NOW() + INTERVAL 6 DAY, NOW() + INTERVAL 9 DAY,
       1, NOW() - INTERVAL 2 DAY, NULL,
       'N', NULL),
      (8, 7, 'https://loremflickr.com/600/400/swim-goggles?lock=71',
       '입문용 수영복 추천 부탁드려요 (DUMMY-071)', '수영 처음 시작하는데 어떤 수영복 사야 할지 모르겠어요. 제안 부탁드립니다.', 70000, 58,
       NOW() - INTERVAL 4 DAY, NOW() + INTERVAL 5 DAY, NOW() + INTERVAL 6 DAY,
       1, NOW() - INTERVAL 4 DAY, NULL,
       'N', NULL),
      (2, 8, 'https://loremflickr.com/600/400/sports-gloves?lock=72',
       '장갑 상태 좋은 거 구합니다 (DUMMY-072)', '평소 쓸 장갑 찾고 있어요. 사용감 적은 제품으로 제안 부탁드립니다.', 170000, 41,
       NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 8 DAY, NOW() - INTERVAL 7 DAY,
       6, NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 8 DAY,
       'Y', NOW() - INTERVAL 8 DAY),
      (7, 1, 'https://loremflickr.com/600/400/soccer-ball?lock=73',
       '초보자용 공인구 어떤 거 사야 할까요 (DUMMY-073)', '이제 막 시작한 초보입니다. 입문용으로 적당한 공인구 제안 부탁드립니다.', 70000, 20,
       NOW() - INTERVAL 24 DAY, NOW() - INTERVAL 19 DAY, NOW() - INTERVAL 17 DAY,
       3, NOW() - INTERVAL 24 DAY, NOW() - INTERVAL 19 DAY,
       'N', NULL),
      (7, 2, 'https://loremflickr.com/600/400/tennis-racket?lock=74',
       '연습용 드라이버 저렴하게 넘겨주실 분 (DUMMY-074)', '연습용이라 흠집 있어도 괜찮습니다. 가격 위주로 제안 부탁드려요.', 830000, 16,
       NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 6 DAY, NOW() - INTERVAL 5 DAY,
       5, NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 6 DAY,
       'N', NULL),
      (6, 3, 'https://loremflickr.com/600/400/sports-protector?lock=75',
       '보호장비 세트 사이즈 맞는 걸로 구합니다 (DUMMY-075)', '운동 중 부상 방지용 보호장비 세트 찾고 있어요. 사이즈 잘 맞는 제품이면 좋겠습니다.', 80000, 14,
       NOW() - INTERVAL 5 DAY, NOW() - INTERVAL 2 DAY, NOW() + INTERVAL 1 DAY,
       2, NOW() - INTERVAL 5 DAY, NULL,
       'N', NULL),
      (4, 4, 'https://loremflickr.com/600/400/sportswear?lock=76',
       '계절용 운동복 추천 부탁드립니다 (DUMMY-076)', '날씨에 맞춰 입을 운동복 찾고 있어요. 브랜드는 크게 상관없습니다.', 50000, 53,
       NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 10 DAY, NOW() - INTERVAL 9 DAY,
       5, NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 10 DAY,
       'N', NULL),
      (10, 5, 'https://loremflickr.com/600/400/dumbbell?lock=77',
       '홈트용 홈트 용품 구합니다 (DUMMY-077)', '집에서 운동할 때 쓸 홈트 용품 찾고 있어요. 부피 너무 크지 않은 제품이면 좋겠습니다.', 140000, 60,
       NOW() - INTERVAL 3 DAY, NOW() + INTERVAL 6 DAY, NOW() + INTERVAL 8 DAY,
       1, NOW() - INTERVAL 3 DAY, NULL,
       'N', NULL),
      (10, 6, 'https://loremflickr.com/600/400/outdoor-gear?lock=78',
       '초보자용 캠핑 의자 추천 부탁드려요 (DUMMY-078)', '아웃도어 입문이라 어떤 캠핑 의자 사야 할지 모르겠어요. 추천 및 제안 부탁드립니다.', 670000, 38,
       NOW() - INTERVAL 13 DAY, NOW() - INTERVAL 9 DAY, NOW() - INTERVAL 7 DAY,
       3, NOW() - INTERVAL 13 DAY, NOW() - INTERVAL 9 DAY,
       'N', NULL),
      (5, 7, 'https://loremflickr.com/600/400/swimming-pool?lock=79',
       '수영 수경 구합니다 (DUMMY-079)', '수영장 다닐 때 쓸 수경 찾고 있어요. 사이즈/색상 협의 가능합니다.', 150000, 36,
       NOW() - INTERVAL 22 DAY, NOW() - INTERVAL 16 DAY, NOW() - INTERVAL 13 DAY,
       4, NOW() - INTERVAL 22 DAY, NOW() - INTERVAL 16 DAY,
       'N', NULL),
      (10, 8, 'https://loremflickr.com/600/400/backpack?lock=80',
       '백팩 상태 좋은 거 구합니다 (DUMMY-080)', '평소 쓸 백팩 찾고 있어요. 사용감 적은 제품으로 제안 부탁드립니다.', 110000, 44,
       NOW() - INTERVAL 13 DAY, NOW() - INTERVAL 8 DAY, NOW() - INTERVAL 5 DAY,
       3, NOW() - INTERVAL 13 DAY, NOW() - INTERVAL 8 DAY,
       'N', NULL),
      (10, 1, 'https://loremflickr.com/600/400/volleyball?lock=81',
       '연습용 공용 공인구 상태 좋은 거 구합니다 (DUMMY-081)', '연습용 공 동호회에서 쓸 공 찾고 있어요. 사용감 적고 바람 빠짐 없는 제품이면 좋겠습니다.', 40000, 50,
       NOW() - INTERVAL 21 DAY, NOW() - INTERVAL 15 DAY, NOW() - INTERVAL 12 DAY,
       3, NOW() - INTERVAL 21 DAY, NOW() - INTERVAL 15 DAY,
       'N', NULL),
      (9, 2, 'https://loremflickr.com/600/400/golf-club?lock=82',
       '드라이버 중급자용으로 제안 부탁드려요 (DUMMY-082)', '핸디/실력 중급 정도입니다. 무난하게 쓸 수 있는 드라이버 찾고 있어요.', 510000, 41,
       NOW(), NOW() + INTERVAL 7 DAY, NOW() + INTERVAL 9 DAY,
       1, NOW(), NULL,
       'N', NULL),
      (7, 3, 'https://loremflickr.com/600/400/elbow-pad?lock=83',
       '손목 보호대 사이즈 맞는 걸로 구합니다 (DUMMY-083)', '운동 중 부상 방지용 손목 보호대 찾고 있어요. 사이즈 잘 맞는 제품이면 좋겠습니다.', 80000, 23,
       NOW() - INTERVAL 3 DAY, NOW() + INTERVAL 6 DAY, NOW() + INTERVAL 7 DAY,
       1, NOW() - INTERVAL 3 DAY, NULL,
       'N', NULL),
      (9, 4, 'https://loremflickr.com/600/400/sports-jacket?lock=84',
       '계절용 레깅스 추천 부탁드립니다 (DUMMY-084)', '날씨에 맞춰 입을 레깅스 찾고 있어요. 브랜드는 크게 상관없습니다.', 90000, 41,
       NOW() - INTERVAL 25 DAY, NOW() - INTERVAL 19 DAY, NOW() - INTERVAL 17 DAY,
       5, NOW() - INTERVAL 25 DAY, NOW() - INTERVAL 19 DAY,
       'N', NULL),
      (4, 5, 'https://loremflickr.com/600/400/gym?lock=85',
       '입문용 요가 매트 가격대 맞춰 구해요 (DUMMY-085)', '운동 입문이라 너무 비싸지 않은 요가 매트으로 제안 부탁드립니다.', 100000, 53,
       NOW() - INTERVAL 18 DAY, NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 11 DAY,
       6, NOW() - INTERVAL 18 DAY, NOW() - INTERVAL 12 DAY,
       'Y', NOW() - INTERVAL 12 DAY),
      (6, 6, 'https://loremflickr.com/600/400/ski-equipment?lock=86',
       '가족용 캠핑 의자 여러 개 구합니다 (DUMMY-086)', '가족이 다 같이 쓸 캠핑 의자 여러 세트 필요합니다.', 510000, 1,
       NOW() - INTERVAL 2 DAY, NOW() + INTERVAL 2 DAY, NOW() + INTERVAL 4 DAY,
       1, NOW() - INTERVAL 2 DAY, NULL,
       'N', NULL),
      (5, 7, 'https://loremflickr.com/600/400/swimsuit?lock=87',
       '대회용 수경 상태 좋은 거 구해요 (DUMMY-087)', '대회 나갈 일이 있어서 상태 좋은 수경 찾고 있습니다.', 90000, 21,
       NOW() - INTERVAL 9 DAY, NOW() - INTERVAL 2 DAY, NOW() + INTERVAL 2 DAY,
       2, NOW() - INTERVAL 9 DAY, NULL,
       'N', NULL),
      (9, 8, 'https://loremflickr.com/600/400/sports-bag?lock=88',
       '스포츠 잡화 상태 좋은 거 구합니다 (DUMMY-088)', '평소 쓸 스포츠 잡화 찾고 있어요. 사용감 적은 제품으로 제안 부탁드립니다.', 100000, 60,
       NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 8 DAY, NOW() - INTERVAL 5 DAY,
       3, NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 8 DAY,
       'N', NULL),
      (9, 1, 'https://loremflickr.com/600/400/basketball?lock=89',
       '시합용 시합용 공 새 제품으로 구해요 (DUMMY-089)', '동호회 시합에 쓸 공인구라 상태 깨끗한 제품으로 부탁드립니다.', 70000, 48,
       NOW() - INTERVAL 3 DAY, NOW() + INTERVAL 6 DAY, NOW() + INTERVAL 9 DAY,
       1, NOW() - INTERVAL 3 DAY, NULL,
       'N', NULL),
      (1, 2, 'https://loremflickr.com/600/400/baseball-bat?lock=90',
       '피팅 포함 드라이버 구합니다 (DUMMY-090)', '제 체형에 맞는 피팅값으로 조정 가능한 드라이버 찾고 있습니다.', 480000, 5,
       NOW() - INTERVAL 17 DAY, NOW() - INTERVAL 11 DAY, NOW() - INTERVAL 8 DAY,
       3, NOW() - INTERVAL 17 DAY, NOW() - INTERVAL 11 DAY,
       'N', NULL),
      (10, 3, 'https://loremflickr.com/600/400/knee-brace?lock=91',
       '운동 시 착용할 무릎 보호대 추천받습니다 (DUMMY-091)', '관절 보호 목적으로 착용할 무릎 보호대 추천 및 제안 부탁드립니다.', 60000, 23,
       NOW() - INTERVAL 21 DAY, NOW() - INTERVAL 15 DAY, NOW() - INTERVAL 12 DAY,
       4, NOW() - INTERVAL 21 DAY, NOW() - INTERVAL 15 DAY,
       'N', NULL),
      (6, 4, 'https://loremflickr.com/600/400/running-shoes?lock=92',
       '가성비 기능성 의류 구성으로 구합니다 (DUMMY-092)', '여러 벌 필요해서 가성비 좋은 기능성 의류 구성으로 제안 부탁드려요.', 120000, 44,
       NOW() - INTERVAL 2 DAY, NOW() + INTERVAL 3 DAY, NOW() + INTERVAL 5 DAY,
       1, NOW() - INTERVAL 2 DAY, NULL,
       'N', NULL),
      (4, 5, 'https://loremflickr.com/600/400/yoga-mat?lock=93',
       '홈트용 아령 세트 구합니다 (DUMMY-093)', '집에서 운동할 때 쓸 아령 세트 찾고 있어요. 부피 너무 크지 않은 제품이면 좋겠습니다.', 110000, 20,
       NOW() - INTERVAL 4 DAY, NOW() + INTERVAL 7 DAY, NOW() + INTERVAL 10 DAY,
       1, NOW() - INTERVAL 4 DAY, NULL,
       'N', NULL),
      (4, 6, 'https://loremflickr.com/600/400/camping-tent?lock=94',
       '초보자용 텐트 추천 부탁드려요 (DUMMY-094)', '아웃도어 입문이라 어떤 텐트 사야 할지 모르겠어요. 추천 및 제안 부탁드립니다.', 500000, 47,
       NOW() - INTERVAL 2 DAY, NOW() + INTERVAL 6 DAY, NOW() + INTERVAL 9 DAY,
       1, NOW() - INTERVAL 2 DAY, NULL,
       'N', NULL),
      (2, 7, 'https://loremflickr.com/600/400/swim-goggles?lock=95',
       '대회용 수모 세트 상태 좋은 거 구해요 (DUMMY-095)', '대회 나갈 일이 있어서 상태 좋은 수모 세트 찾고 있습니다.', 80000, 53,
       NOW() - INTERVAL 2 DAY, NOW() + INTERVAL 2 DAY, NOW() + INTERVAL 4 DAY,
       1, NOW() - INTERVAL 2 DAY, NULL,
       'N', NULL),
      (1, 8, 'https://loremflickr.com/600/400/sports-gloves?lock=96',
       '가성비 백팩 구합니다 (DUMMY-096)', '예산 맞춰서 가성비 좋은 백팩으로 제안 부탁드려요.', 80000, 45,
       NOW() - INTERVAL 2 DAY, NOW() + INTERVAL 1 DAY, NOW() + INTERVAL 2 DAY,
       1, NOW() - INTERVAL 2 DAY, NULL,
       'N', NULL),
      (3, 1, 'https://loremflickr.com/600/400/soccer-ball?lock=97',
       '초보자용 연습용 공 어떤 거 사야 할까요 (DUMMY-097)', '이제 막 시작한 초보입니다. 입문용으로 적당한 연습용 공 제안 부탁드립니다.', 110000, 40,
       NOW() - INTERVAL 13 DAY, NOW() - INTERVAL 10 DAY, NOW() - INTERVAL 7 DAY,
       5, NOW() - INTERVAL 13 DAY, NOW() - INTERVAL 10 DAY,
       'N', NULL),
      (8, 2, 'https://loremflickr.com/600/400/tennis-racket?lock=98',
       '피팅 포함 드라이버 구합니다 (DUMMY-098)', '제 체형에 맞는 피팅값으로 조정 가능한 드라이버 찾고 있습니다.', 510000, 28,
       NOW() - INTERVAL 1 DAY, NOW() + INTERVAL 1 DAY, NOW() + INTERVAL 3 DAY,
       1, NOW() - INTERVAL 1 DAY, NULL,
       'N', NULL),
      (2, 3, 'https://loremflickr.com/600/400/sports-protector?lock=99',
       '손목 보호대 사이즈 맞는 걸로 구합니다 (DUMMY-099)', '운동 중 부상 방지용 손목 보호대 찾고 있어요. 사이즈 잘 맞는 제품이면 좋겠습니다.', 60000, 25,
       NOW(), NOW() + INTERVAL 5 DAY, NOW() + INTERVAL 8 DAY,
       1, NOW(), NULL,
       'N', NULL),
      (3, 4, 'https://loremflickr.com/600/400/sportswear?lock=100',
       '운동용 기능성 의류 사이즈 맞는 거 구해요 (DUMMY-100)', '평소 운동할 때 입을 기능성 의류 찾고 있습니다. 신축성 좋은 제품이면 좋겠어요.', 170000, 9,
       NOW() - INTERVAL 19 DAY, NOW() - INTERVAL 16 DAY, NOW() - INTERVAL 15 DAY,
       4, NOW() - INTERVAL 19 DAY, NOW() - INTERVAL 16 DAY,
       'N', NULL);

-- BID 1~2건씩 (auction_title로 auction_idx를, item_name으로 item_idx를 서브쿼리 조회)
INSERT INTO bid (
    auction_idx, bidder_idx, item_idx, bid_price, bid_quantity,
    bid_message, bid_status_idx, bid_regdate, bid_moddate
) VALUES
      ((SELECT auction_idx FROM auction WHERE auction_title = '초보자용 공인구 어떤 거 사야 할까요 (DUMMY-001)' LIMIT 1), 10, (SELECT item_idx FROM item WHERE item_name = '발볼 넓은 축구 스파이크 B' LIMIT 1), 108000, 1,
    '직접 사용해본 제품이라 상태는 자신 있습니다. 합리적인 가격 제안드려요.', 1, NOW(), NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '연습용 아이언 세트 저렴하게 넘겨주실 분 (DUMMY-002)' LIMIT 1), 5, (SELECT item_idx FROM item WHERE item_name = '아이언 세트 - 거의 새 제품' LIMIT 1), 728000, 1,
 '직접 사용해본 제품이라 상태는 자신 있습니다. 합리적인 가격 제안드려요.', 1, NOW() - INTERVAL 4 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '연습용 아이언 세트 저렴하게 넘겨주실 분 (DUMMY-002)' LIMIT 1), 7, (SELECT item_idx FROM item WHERE item_name = '연습용 아이언 세트' LIMIT 1), 763000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 1, NOW() - INTERVAL 3 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '새 제품 보호장비 세트 저렴하게 구합니다 (DUMMY-003)' LIMIT 1), 5, (SELECT item_idx FROM item WHERE item_name = '손목/팔꿈치 보호대 세트' LIMIT 1), 49000, 1,
 '사용감은 조금 있지만 기능상 문제 없습니다. 좋은 가격에 드릴게요.', 4, NOW() - INTERVAL 16 DAY, NOW() - INTERVAL 13 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '운동용 레깅스 사이즈 맞는 거 구해요 (DUMMY-004)' LIMIT 1), 3, (SELECT item_idx FROM item WHERE item_name = '기능성 운동 레깅스 (블랙)' LIMIT 1), 54000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 1, NOW() + INTERVAL 6 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '홈트용 홈트 용품 구합니다 (DUMMY-005)' LIMIT 1), 5, (SELECT item_idx FROM item WHERE item_name = '10km 대회용 러닝화 - 쿠션 좋은 모델' LIMIT 1), 245000, 1,
 '사용감은 조금 있지만 기능상 문제 없습니다. 좋은 가격에 드릴게요.', 2, NOW() - INTERVAL 22 DAY, NOW() - INTERVAL 19 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '홈트용 홈트 용품 구합니다 (DUMMY-005)' LIMIT 1), 8, (SELECT item_idx FROM item WHERE item_name = '경량 러닝화 - 전시 제품' LIMIT 1), 274000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 3, NOW() - INTERVAL 20 DAY, NOW() - INTERVAL 19 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '텐트 풀세트로 구합니다 (DUMMY-006)' LIMIT 1), 2, (SELECT item_idx FROM item WHERE item_name = '스키 풀세트 (구형 장비)' LIMIT 1), 363000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 1, NOW() - INTERVAL 8 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '가성비 수영복 구성으로 구합니다 (DUMMY-007)' LIMIT 1), 1, (SELECT item_idx FROM item WHERE item_name = '수영 입문 세트 A (수경+수모+수영복)' LIMIT 1), 50000, 1,
 '직접 사용해본 제품이라 상태는 자신 있습니다. 합리적인 가격 제안드려요.', 1, NOW() + INTERVAL 2 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '가성비 수영복 구성으로 구합니다 (DUMMY-007)' LIMIT 1), 3, (SELECT item_idx FROM item WHERE item_name = '브랜드 수영 세트 C' LIMIT 1), 48000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 1, NOW() + INTERVAL 2 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '스포츠 잡화 상태 좋은 거 구합니다 (DUMMY-008)' LIMIT 1), 8, (SELECT item_idx FROM item WHERE item_name = '대용량 스포츠 백팩 (신발주머니 포함)' LIMIT 1), 98000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 2, NOW() - INTERVAL 9 DAY, NOW() - INTERVAL 9 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '스포츠 잡화 상태 좋은 거 구합니다 (DUMMY-008)' LIMIT 1), 2, (SELECT item_idx FROM item WHERE item_name = '겨울철 야외 러닝용 스마트폰 터치 장갑' LIMIT 1), 94000, 1,
 '거의 새 제품 수준입니다. 박스/구성품 모두 포함되어 있어요.', 3, NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 9 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '연습용 공용 공인구 상태 좋은 거 구합니다 (DUMMY-009)' LIMIT 1), 10, (SELECT item_idx FROM item WHERE item_name = 'KBL 공식 시합용 농구공' LIMIT 1), 108000, 1,
 '상태 좋은 제품으로 제안드립니다. 직거래/택배 모두 가능합니다.', 1, NOW() + INTERVAL 1 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '입문용 드라이버 가성비 좋은 걸로 구해요 (DUMMY-010)' LIMIT 1), 8, (SELECT item_idx FROM item WHERE item_name = '중고 아이언 세트 - 사용감 있음' LIMIT 1), 840000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 2, NOW() - INTERVAL 10 DAY, NOW() - INTERVAL 9 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '손목 보호대 사이즈 맞는 걸로 구합니다 (DUMMY-011)' LIMIT 1), 8, (SELECT item_idx FROM item WHERE item_name = '축구용 정강이 보호대 (스타킹 포함)' LIMIT 1), 41000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 2, NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 8 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '가성비 운동복 구성으로 구합니다 (DUMMY-012)' LIMIT 1), 2, (SELECT item_idx FROM item WHERE item_name = '방수 자켓 - 등산/캠핑용' LIMIT 1), 132000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 1, NOW(), NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '가성비 운동복 구성으로 구합니다 (DUMMY-012)' LIMIT 1), 3, (SELECT item_idx FROM item WHERE item_name = '드라이핏 라운드 티셔츠 세트' LIMIT 1), 132000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 1, NOW() + INTERVAL 1 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '입문용 아령 세트 가격대 맞춰 구해요 (DUMMY-013)' LIMIT 1), 2, (SELECT item_idx FROM item WHERE item_name = '아령 세트 + 두꺼운 매트' LIMIT 1), 265000, 1,
 '거의 새 제품 수준입니다. 박스/구성품 모두 포함되어 있어요.', 2, NOW() - INTERVAL 21 DAY, NOW() - INTERVAL 15 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '캠핑 의자 풀세트로 구합니다 (DUMMY-014)' LIMIT 1), 1, (SELECT item_idx FROM item WHERE item_name = '스키 풀세트 (구형 장비)' LIMIT 1), 234000, 1,
 '직접 사용해본 제품이라 상태는 자신 있습니다. 합리적인 가격 제안드려요.', 2, NOW() - INTERVAL 17 DAY, NOW() - INTERVAL 17 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '캠핑 의자 풀세트로 구합니다 (DUMMY-014)' LIMIT 1), 4, (SELECT item_idx FROM item WHERE item_name = '스키 풀세트 (구형 장비)' LIMIT 1), 238000, 1,
 '상태 좋은 제품으로 제안드립니다. 직거래/택배 모두 가능합니다.', 3, NOW() - INTERVAL 19 DAY, NOW() - INTERVAL 17 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '입문용 수모 세트 추천 부탁드려요 (DUMMY-015)' LIMIT 1), 8, (SELECT item_idx FROM item WHERE item_name = '브랜드 수영 세트 C' LIMIT 1), 45000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 2, NOW() - INTERVAL 11 DAY, NOW() - INTERVAL 9 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '입문용 수모 세트 추천 부탁드려요 (DUMMY-015)' LIMIT 1), 10, (SELECT item_idx FROM item WHERE item_name = '수영 입문 세트 A (수경+수모+수영복)' LIMIT 1), 50000, 1,
 '거의 새 제품 수준입니다. 박스/구성품 모두 포함되어 있어요.', 3, NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 9 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '백팩 상태 좋은 거 구합니다 (DUMMY-016)' LIMIT 1), 2, (SELECT item_idx FROM item WHERE item_name = '리조트 숙박권 1박' LIMIT 1), 114000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 1, NOW() - INTERVAL 6 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '백팩 상태 좋은 거 구합니다 (DUMMY-016)' LIMIT 1), 8, (SELECT item_idx FROM item WHERE item_name = '겨울철 야외 러닝용 스마트폰 터치 장갑' LIMIT 1), 107000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 1, NOW() - INTERVAL 5 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '실내 연습용 공인구 추천 부탁드려요 (DUMMY-017)' LIMIT 1), 8, (SELECT item_idx FROM item WHERE item_name = '발볼 넓은 축구 스파이크 B' LIMIT 1), 106000, 1,
 '사용감은 조금 있지만 기능상 문제 없습니다. 좋은 가격에 드릴게요.', 1, NOW() - INTERVAL 3 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '실내 연습용 공인구 추천 부탁드려요 (DUMMY-017)' LIMIT 1), 4, (SELECT item_idx FROM item WHERE item_name = 'KBL 공식 시합용 농구공' LIMIT 1), 102000, 1,
 '직접 사용해본 제품이라 상태는 자신 있습니다. 합리적인 가격 제안드려요.', 1, NOW() - INTERVAL 2 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '아이언 세트 중급자용으로 제안 부탁드려요 (DUMMY-018)' LIMIT 1), 5, (SELECT item_idx FROM item WHERE item_name = '중고 아이언 세트 - 사용감 있음' LIMIT 1), 579000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 4, NOW() - INTERVAL 19 DAY, NOW() - INTERVAL 15 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '손목 보호대 사이즈 맞는 걸로 구합니다 (DUMMY-019)' LIMIT 1), 10, (SELECT item_idx FROM item WHERE item_name = '무릎 보호대 세트 - 사용감 적음' LIMIT 1), 61000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 2, NOW() - INTERVAL 17 DAY, NOW() - INTERVAL 17 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '손목 보호대 사이즈 맞는 걸로 구합니다 (DUMMY-019)' LIMIT 1), 8, (SELECT item_idx FROM item WHERE item_name = '손목/팔꿈치 보호대 세트' LIMIT 1), 57000, 1,
 '직접 사용해본 제품이라 상태는 자신 있습니다. 합리적인 가격 제안드려요.', 3, NOW() - INTERVAL 17 DAY, NOW() - INTERVAL 17 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '계절용 운동복 추천 부탁드립니다 (DUMMY-020)' LIMIT 1), 4, (SELECT item_idx FROM item WHERE item_name = '방수 자켓 - 등산/캠핑용' LIMIT 1), 65000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 1, NOW() - INTERVAL 3 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '계절용 운동복 추천 부탁드립니다 (DUMMY-020)' LIMIT 1), 7, (SELECT item_idx FROM item WHERE item_name = '기능성 운동 레깅스 (블랙)' LIMIT 1), 66000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 1, NOW() + INTERVAL 2 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '헬스장에서 쓸 홈트 용품 추천받습니다 (DUMMY-021)' LIMIT 1), 3, (SELECT item_idx FROM item WHERE item_name = '아령 세트 + 두꺼운 매트' LIMIT 1), 261000, 1,
 '사용감은 조금 있지만 기능상 문제 없습니다. 좋은 가격에 드릴게요.', 1, NOW() + INTERVAL 1 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '헬스장에서 쓸 홈트 용품 추천받습니다 (DUMMY-021)' LIMIT 1), 8, (SELECT item_idx FROM item WHERE item_name = '가성비 홈트 세트' LIMIT 1), 257000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 1, NOW(), NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '스키 장비 풀세트로 구합니다 (DUMMY-022)' LIMIT 1), 7, (SELECT item_idx FROM item WHERE item_name = '스키 풀세트 (구형 장비)' LIMIT 1), 619000, 1,
 '거의 새 제품 수준입니다. 박스/구성품 모두 포함되어 있어요.', 1, NOW() + INTERVAL 1 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '스키 장비 풀세트로 구합니다 (DUMMY-022)' LIMIT 1), 3, (SELECT item_idx FROM item WHERE item_name = '스키 풀세트 (구형 장비)' LIMIT 1), 675000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 1, NOW() - INTERVAL 1 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '가성비 수영복 구성으로 구합니다 (DUMMY-023)' LIMIT 1), 6, (SELECT item_idx FROM item WHERE item_name = '브랜드 수영 세트 C' LIMIT 1), 113000, 1,
 '상태 좋은 제품으로 제안드립니다. 직거래/택배 모두 가능합니다.', 1, NOW() + INTERVAL 2 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '가성비 수영복 구성으로 구합니다 (DUMMY-023)' LIMIT 1), 8, (SELECT item_idx FROM item WHERE item_name = '수영 세트 B - 수경 사용감 있음' LIMIT 1), 100000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 1, NOW() + INTERVAL 2 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '새 제품 백팩 깨끗한 걸로 구해요 (DUMMY-024)' LIMIT 1), 2, (SELECT item_idx FROM item WHERE item_name = '콘서트 티켓 2장' LIMIT 1), 188000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 5, NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 13 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '새 제품 백팩 깨끗한 걸로 구해요 (DUMMY-024)' LIMIT 1), 7, (SELECT item_idx FROM item WHERE item_name = '대용량 스포츠 백팩 (신발주머니 포함)' LIMIT 1), 185000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 5, NOW() - INTERVAL 18 DAY, NOW() - INTERVAL 13 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '시합용 연습용 공 새 제품으로 구해요 (DUMMY-025)' LIMIT 1), 6, (SELECT item_idx FROM item WHERE item_name = '프리미어리그 공인구 - 미개봉 새제품' LIMIT 1), 75000, 1,
 '거의 새 제품 수준입니다. 박스/구성품 모두 포함되어 있어요.', 3, NOW() - INTERVAL 13 DAY, NOW() - INTERVAL 13 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '시합용 연습용 공 새 제품으로 구해요 (DUMMY-025)' LIMIT 1), 1, (SELECT item_idx FROM item WHERE item_name = '발볼 넓은 축구 스파이크 B' LIMIT 1), 73000, 1,
 '직접 사용해본 제품이라 상태는 자신 있습니다. 합리적인 가격 제안드려요.', 3, NOW() - INTERVAL 13 DAY, NOW() - INTERVAL 13 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '라켓/클럽 중급자용으로 제안 부탁드려요 (DUMMY-026)' LIMIT 1), 3, (SELECT item_idx FROM item WHERE item_name = '중고 아이언 세트 - 사용감 있음' LIMIT 1), 300000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 1, NOW() - INTERVAL 6 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '재활용 보호장비 세트 상태 좋은 거 구해요 (DUMMY-027)' LIMIT 1), 8, (SELECT item_idx FROM item WHERE item_name = '손목/팔꿈치 보호대 세트' LIMIT 1), 29000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 3, NOW() - INTERVAL 15 DAY, NOW() - INTERVAL 12 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '재활용 보호장비 세트 상태 좋은 거 구해요 (DUMMY-027)' LIMIT 1), 5, (SELECT item_idx FROM item WHERE item_name = '무릎 보호대 세트 - 사용감 적음' LIMIT 1), 31000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 3, NOW() - INTERVAL 13 DAY, NOW() - INTERVAL 12 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '계절용 운동복 추천 부탁드립니다 (DUMMY-028)' LIMIT 1), 8, (SELECT item_idx FROM item WHERE item_name = '기능성 운동 레깅스 (블랙)' LIMIT 1), 197000, 1,
 '직접 사용해본 제품이라 상태는 자신 있습니다. 합리적인 가격 제안드려요.', 1, NOW() - INTERVAL 2 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '홈트용 러닝화 구합니다 (DUMMY-029)' LIMIT 1), 8, (SELECT item_idx FROM item WHERE item_name = '가성비 홈트 세트' LIMIT 1), 241000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 3, NOW() - INTERVAL 17 DAY, NOW() - INTERVAL 15 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '홈트용 러닝화 구합니다 (DUMMY-029)' LIMIT 1), 5, (SELECT item_idx FROM item WHERE item_name = '초보자용 러닝화 - 한 달 사용' LIMIT 1), 238000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 3, NOW() - INTERVAL 16 DAY, NOW() - INTERVAL 15 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '중고 스키 장비 상태 좋은 거 구해요 (DUMMY-030)' LIMIT 1), 1, (SELECT item_idx FROM item WHERE item_name = '스키 풀세트 (구형 장비)' LIMIT 1), 423000, 1,
 '직접 사용해본 제품이라 상태는 자신 있습니다. 합리적인 가격 제안드려요.', 1, NOW() - INTERVAL 1 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '중고 스키 장비 상태 좋은 거 구해요 (DUMMY-030)' LIMIT 1), 7, (SELECT item_idx FROM item WHERE item_name = '스키 풀세트 (구형 장비)' LIMIT 1), 466000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 1, NOW() + INTERVAL 6 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '가성비 수영복 구성으로 구합니다 (DUMMY-031)' LIMIT 1), 4, (SELECT item_idx FROM item WHERE item_name = '수영 입문 세트 A (수경+수모+수영복)' LIMIT 1), 168000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 1, NOW(), NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '가성비 수영복 구성으로 구합니다 (DUMMY-031)' LIMIT 1), 10, (SELECT item_idx FROM item WHERE item_name = '수영 세트 B - 수경 사용감 있음' LIMIT 1), 169000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 1, NOW(), NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '스포츠 잡화 상태 좋은 거 구합니다 (DUMMY-032)' LIMIT 1), 10, (SELECT item_idx FROM item WHERE item_name = '겨울철 야외 러닝용 스마트폰 터치 장갑' LIMIT 1), 100000, 1,
 '상태 좋은 제품으로 제안드립니다. 직거래/택배 모두 가능합니다.', 1, NOW() - INTERVAL 5 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '스포츠 잡화 상태 좋은 거 구합니다 (DUMMY-032)' LIMIT 1), 6, (SELECT item_idx FROM item WHERE item_name = '리조트 숙박권 1박' LIMIT 1), 94000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 1, NOW() - INTERVAL 7 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '시합용 공용 공인구 상태 좋은 거 구합니다 (DUMMY-033)' LIMIT 1), 9, (SELECT item_idx FROM item WHERE item_name = 'KBL 공식 시합용 농구공' LIMIT 1), 82000, 1,
 '거의 새 제품 수준입니다. 박스/구성품 모두 포함되어 있어요.', 2, NOW() - INTERVAL 11 DAY, NOW() - INTERVAL 9 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '연습용 라켓/클럽 저렴하게 넘겨주실 분 (DUMMY-034)' LIMIT 1), 5, (SELECT item_idx FROM item WHERE item_name = '중고 아이언 세트 - 사용감 있음' LIMIT 1), 724000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 2, NOW() - INTERVAL 10 DAY, NOW() - INTERVAL 5 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '연습용 라켓/클럽 저렴하게 넘겨주실 분 (DUMMY-034)' LIMIT 1), 6, (SELECT item_idx FROM item WHERE item_name = '아이언 세트 - 거의 새 제품' LIMIT 1), 653000, 1,
 '사용감은 조금 있지만 기능상 문제 없습니다. 좋은 가격에 드릴게요.', 3, NOW() - INTERVAL 5 DAY, NOW() - INTERVAL 5 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '재활용 무릎 보호대 상태 좋은 거 구해요 (DUMMY-035)' LIMIT 1), 1, (SELECT item_idx FROM item WHERE item_name = '헬스용 손목 스트랩 + 무릎 슬리브' LIMIT 1), 29000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 2, NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 9 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '재활용 무릎 보호대 상태 좋은 거 구해요 (DUMMY-035)' LIMIT 1), 5, (SELECT item_idx FROM item WHERE item_name = '무릎 보호대 세트 - 사용감 적음' LIMIT 1), 30000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 3, NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 9 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '계절용 기능성 의류 추천 부탁드립니다 (DUMMY-036)' LIMIT 1), 4, (SELECT item_idx FROM item WHERE item_name = '방수 자켓 - 등산/캠핑용' LIMIT 1), 135000, 1,
 '직접 사용해본 제품이라 상태는 자신 있습니다. 합리적인 가격 제안드려요.', 1, NOW() + INTERVAL 3 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '계절용 기능성 의류 추천 부탁드립니다 (DUMMY-036)' LIMIT 1), 8, (SELECT item_idx FROM item WHERE item_name = '기능성 운동 레깅스 (블랙)' LIMIT 1), 155000, 1,
 '사용감은 조금 있지만 기능상 문제 없습니다. 좋은 가격에 드릴게요.', 1, NOW() - INTERVAL 1 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '홈트용 요가 매트 구합니다 (DUMMY-037)' LIMIT 1), 7, (SELECT item_idx FROM item WHERE item_name = '가성비 홈트 세트' LIMIT 1), 193000, 1,
 '상태 좋은 제품으로 제안드립니다. 직거래/택배 모두 가능합니다.', 5, NOW() - INTERVAL 16 DAY, NOW() - INTERVAL 15 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '홈트용 요가 매트 구합니다 (DUMMY-037)' LIMIT 1), 2, (SELECT item_idx FROM item WHERE item_name = '초보자용 러닝화 - 한 달 사용' LIMIT 1), 220000, 1,
 '상태 좋은 제품으로 제안드립니다. 직거래/택배 모두 가능합니다.', 5, NOW() - INTERVAL 18 DAY, NOW() - INTERVAL 15 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '초보자용 캠핑 의자 추천 부탁드려요 (DUMMY-038)' LIMIT 1), 7, (SELECT item_idx FROM item WHERE item_name = '스키 풀세트 (구형 장비)' LIMIT 1), 648000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 1, NOW() - INTERVAL 3 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '수영 수영복 구합니다 (DUMMY-039)' LIMIT 1), 7, (SELECT item_idx FROM item WHERE item_name = '브랜드 수영 세트 C' LIMIT 1), 194000, 1,
 '직접 사용해본 제품이라 상태는 자신 있습니다. 합리적인 가격 제안드려요.', 3, NOW() - INTERVAL 11 DAY, NOW() - INTERVAL 11 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '수영 수영복 구합니다 (DUMMY-039)' LIMIT 1), 2, (SELECT item_idx FROM item WHERE item_name = '수영 입문 세트 A (수경+수모+수영복)' LIMIT 1), 197000, 1,
 '거의 새 제품 수준입니다. 박스/구성품 모두 포함되어 있어요.', 3, NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 11 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '선물용 스포츠 잡화 추천 부탁드려요 (DUMMY-040)' LIMIT 1), 8, (SELECT item_idx FROM item WHERE item_name = '콘서트 티켓 2장' LIMIT 1), 51000, 1,
 '상태 좋은 제품으로 제안드립니다. 직거래/택배 모두 가능합니다.', 1, NOW() + INTERVAL 3 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '선물용 스포츠 잡화 추천 부탁드려요 (DUMMY-040)' LIMIT 1), 4, (SELECT item_idx FROM item WHERE item_name = '겨울철 야외 러닝용 스마트폰 터치 장갑' LIMIT 1), 47000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 1, NOW(), NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '실내 연습용 시합용 공 추천 부탁드려요 (DUMMY-041)' LIMIT 1), 5, (SELECT item_idx FROM item WHERE item_name = '발볼 넓은 축구 스파이크 B' LIMIT 1), 46000, 1,
 '상태 좋은 제품으로 제안드립니다. 직거래/택배 모두 가능합니다.', 1, NOW() + INTERVAL 5 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '입문용 드라이버 가성비 좋은 걸로 구해요 (DUMMY-042)' LIMIT 1), 4, (SELECT item_idx FROM item WHERE item_name = '연습용 아이언 세트' LIMIT 1), 398000, 1,
 '직접 사용해본 제품이라 상태는 자신 있습니다. 합리적인 가격 제안드려요.', 1, NOW() - INTERVAL 1 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '운동 시 착용할 무릎 보호대 추천받습니다 (DUMMY-043)' LIMIT 1), 4, (SELECT item_idx FROM item WHERE item_name = '헬스용 손목 스트랩 + 무릎 슬리브' LIMIT 1), 83000, 1,
 '직접 사용해본 제품이라 상태는 자신 있습니다. 합리적인 가격 제안드려요.', 1, NOW(), NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '운동용 기능성 의류 사이즈 맞는 거 구해요 (DUMMY-044)' LIMIT 1), 10, (SELECT item_idx FROM item WHERE item_name = '드라이핏 라운드 티셔츠 세트' LIMIT 1), 46000, 1,
 '사용감은 조금 있지만 기능상 문제 없습니다. 좋은 가격에 드릴게요.', 1, NOW() - INTERVAL 1 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '입문용 홈트 용품 가격대 맞춰 구해요 (DUMMY-045)' LIMIT 1), 10, (SELECT item_idx FROM item WHERE item_name = '두꺼운 요가 매트' LIMIT 1), 135000, 1,
 '사용감은 조금 있지만 기능상 문제 없습니다. 좋은 가격에 드릴게요.', 1, NOW() - INTERVAL 1 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '가족용 텐트 여러 개 구합니다 (DUMMY-046)' LIMIT 1), 3, (SELECT item_idx FROM item WHERE item_name = '스키 풀세트 (구형 장비)' LIMIT 1), 228000, 1,
 '사용감은 조금 있지만 기능상 문제 없습니다. 좋은 가격에 드릴게요.', 3, NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 13 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '가족용 텐트 여러 개 구합니다 (DUMMY-046)' LIMIT 1), 1, (SELECT item_idx FROM item WHERE item_name = '스키 풀세트 (구형 장비)' LIMIT 1), 227000, 1,
 '사용감은 조금 있지만 기능상 문제 없습니다. 좋은 가격에 드릴게요.', 2, NOW() - INTERVAL 16 DAY, NOW() - INTERVAL 13 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '가성비 수모 세트 구성으로 구합니다 (DUMMY-047)' LIMIT 1), 7, (SELECT item_idx FROM item WHERE item_name = '수영 입문 세트 A (수경+수모+수영복)' LIMIT 1), 48000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 2, NOW() - INTERVAL 13 DAY, NOW() - INTERVAL 8 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '가성비 스포츠 잡화 구합니다 (DUMMY-048)' LIMIT 1), 8, (SELECT item_idx FROM item WHERE item_name = '겨울철 야외 러닝용 스마트폰 터치 장갑' LIMIT 1), 158000, 1,
 '직접 사용해본 제품이라 상태는 자신 있습니다. 합리적인 가격 제안드려요.', 3, NOW() - INTERVAL 21 DAY, NOW() - INTERVAL 16 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '가성비 스포츠 잡화 구합니다 (DUMMY-048)' LIMIT 1), 9, (SELECT item_idx FROM item WHERE item_name = '콘서트 티켓 2장' LIMIT 1), 171000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 2, NOW() - INTERVAL 17 DAY, NOW() - INTERVAL 16 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '연습용 공용 공인구 상태 좋은 거 구합니다 (DUMMY-049)' LIMIT 1), 1, (SELECT item_idx FROM item WHERE item_name = '발볼 넓은 축구 스파이크 B' LIMIT 1), 136000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 1, NOW() + INTERVAL 2 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '연습용 공용 공인구 상태 좋은 거 구합니다 (DUMMY-049)' LIMIT 1), 10, (SELECT item_idx FROM item WHERE item_name = '인조잔디용 축구 스파이크 A' LIMIT 1), 130000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 1, NOW() + INTERVAL 2 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '피팅 포함 라켓/클럽 구합니다 (DUMMY-050)' LIMIT 1), 6, (SELECT item_idx FROM item WHERE item_name = '중고 아이언 세트 - 사용감 있음' LIMIT 1), 882000, 1,
 '상태 좋은 제품으로 제안드립니다. 직거래/택배 모두 가능합니다.', 1, NOW() - INTERVAL 2 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '재활용 보호장비 세트 상태 좋은 거 구해요 (DUMMY-051)' LIMIT 1), 10, (SELECT item_idx FROM item WHERE item_name = '헬스용 손목 스트랩 + 무릎 슬리브' LIMIT 1), 28000, 1,
 '직접 사용해본 제품이라 상태는 자신 있습니다. 합리적인 가격 제안드려요.', 5, NOW() - INTERVAL 16 DAY, NOW() - INTERVAL 15 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '재활용 보호장비 세트 상태 좋은 거 구해요 (DUMMY-051)' LIMIT 1), 9, (SELECT item_idx FROM item WHERE item_name = '손목/팔꿈치 보호대 세트' LIMIT 1), 28000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 5, NOW() - INTERVAL 20 DAY, NOW() - INTERVAL 15 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '가성비 운동복 구성으로 구합니다 (DUMMY-052)' LIMIT 1), 8, (SELECT item_idx FROM item WHERE item_name = '골프웨어 상하의 세트' LIMIT 1), 154000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 1, NOW() - INTERVAL 3 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '헬스장에서 쓸 요가 매트 추천받습니다 (DUMMY-053)' LIMIT 1), 2, (SELECT item_idx FROM item WHERE item_name = '아령 세트 + 두꺼운 매트' LIMIT 1), 279000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 1, NOW() + INTERVAL 1 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '헬스장에서 쓸 요가 매트 추천받습니다 (DUMMY-053)' LIMIT 1), 6, (SELECT item_idx FROM item WHERE item_name = '두꺼운 요가 매트' LIMIT 1), 277000, 1,
 '사용감은 조금 있지만 기능상 문제 없습니다. 좋은 가격에 드릴게요.', 1, NOW() + INTERVAL 4 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '중고 텐트 상태 좋은 거 구해요 (DUMMY-054)' LIMIT 1), 2, (SELECT item_idx FROM item WHERE item_name = '스키 풀세트 (구형 장비)' LIMIT 1), 182000, 1,
 '상태 좋은 제품으로 제안드립니다. 직거래/택배 모두 가능합니다.', 1, NOW() - INTERVAL 2 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '대회용 수영복 상태 좋은 거 구해요 (DUMMY-055)' LIMIT 1), 10, (SELECT item_idx FROM item WHERE item_name = '수영 입문 세트 A (수경+수모+수영복)' LIMIT 1), 118000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 1, NOW() - INTERVAL 1 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '대회용 수영복 상태 좋은 거 구해요 (DUMMY-055)' LIMIT 1), 9, (SELECT item_idx FROM item WHERE item_name = '브랜드 수영 세트 C' LIMIT 1), 115000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 1, NOW() + INTERVAL 5 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '선물용 스포츠 잡화 추천 부탁드려요 (DUMMY-056)' LIMIT 1), 10, (SELECT item_idx FROM item WHERE item_name = '리조트 숙박권 1박' LIMIT 1), 133000, 1,
 '직접 사용해본 제품이라 상태는 자신 있습니다. 합리적인 가격 제안드려요.', 1, NOW() + INTERVAL 3 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '선물용 스포츠 잡화 추천 부탁드려요 (DUMMY-056)' LIMIT 1), 5, (SELECT item_idx FROM item WHERE item_name = '콘서트 티켓 2장' LIMIT 1), 129000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 1, NOW() + INTERVAL 3 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '초보자용 연습용 공 어떤 거 사야 할까요 (DUMMY-057)' LIMIT 1), 9, (SELECT item_idx FROM item WHERE item_name = '인조잔디용 축구 스파이크 A' LIMIT 1), 66000, 1,
 '거의 새 제품 수준입니다. 박스/구성품 모두 포함되어 있어요.', 2, NOW() - INTERVAL 13 DAY, NOW() - INTERVAL 11 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '피팅 포함 아이언 세트 구합니다 (DUMMY-058)' LIMIT 1), 1, (SELECT item_idx FROM item WHERE item_name = '연습용 아이언 세트' LIMIT 1), 743000, 1,
 '거의 새 제품 수준입니다. 박스/구성품 모두 포함되어 있어요.', 2, NOW() - INTERVAL 10 DAY, NOW() - INTERVAL 6 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '피팅 포함 아이언 세트 구합니다 (DUMMY-058)' LIMIT 1), 3, (SELECT item_idx FROM item WHERE item_name = '중고 아이언 세트 - 사용감 있음' LIMIT 1), 752000, 1,
 '사용감은 조금 있지만 기능상 문제 없습니다. 좋은 가격에 드릴게요.', 3, NOW() - INTERVAL 6 DAY, NOW() - INTERVAL 6 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '재활용 보호장비 세트 상태 좋은 거 구해요 (DUMMY-059)' LIMIT 1), 2, (SELECT item_idx FROM item WHERE item_name = '축구용 정강이 보호대 (스타킹 포함)' LIMIT 1), 55000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 1, NOW() - INTERVAL 1 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '운동용 기능성 의류 사이즈 맞는 거 구해요 (DUMMY-060)' LIMIT 1), 7, (SELECT item_idx FROM item WHERE item_name = '드라이핏 라운드 티셔츠 세트' LIMIT 1), 105000, 1,
 '거의 새 제품 수준입니다. 박스/구성품 모두 포함되어 있어요.', 2, NOW() - INTERVAL 16 DAY, NOW() - INTERVAL 13 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '홈트용 홈트 용품 구합니다 (DUMMY-061)' LIMIT 1), 6, (SELECT item_idx FROM item WHERE item_name = '초보자용 러닝화 - 한 달 사용' LIMIT 1), 113000, 1,
 '사용감은 조금 있지만 기능상 문제 없습니다. 좋은 가격에 드릴게요.', 1, NOW() - INTERVAL 2 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '홈트용 홈트 용품 구합니다 (DUMMY-061)' LIMIT 1), 2, (SELECT item_idx FROM item WHERE item_name = '가성비 홈트 세트' LIMIT 1), 111000, 1,
 '상태 좋은 제품으로 제안드립니다. 직거래/택배 모두 가능합니다.', 1, NOW() + INTERVAL 2 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '중고 스키 장비 상태 좋은 거 구해요 (DUMMY-062)' LIMIT 1), 8, (SELECT item_idx FROM item WHERE item_name = '스키 풀세트 (구형 장비)' LIMIT 1), 659000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 1, NOW() + INTERVAL 3 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '입문용 수영복 추천 부탁드려요 (DUMMY-063)' LIMIT 1), 9, (SELECT item_idx FROM item WHERE item_name = '수영 세트 B - 수경 사용감 있음' LIMIT 1), 85000, 1,
 '상태 좋은 제품으로 제안드립니다. 직거래/택배 모두 가능합니다.', 1, NOW() + INTERVAL 3 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '입문용 수영복 추천 부탁드려요 (DUMMY-063)' LIMIT 1), 2, (SELECT item_idx FROM item WHERE item_name = '수영 입문 세트 A (수경+수모+수영복)' LIMIT 1), 90000, 1,
 '직접 사용해본 제품이라 상태는 자신 있습니다. 합리적인 가격 제안드려요.', 1, NOW() + INTERVAL 6 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '새 제품 장갑 깨끗한 걸로 구해요 (DUMMY-064)' LIMIT 1), 10, (SELECT item_idx FROM item WHERE item_name = '리조트 숙박권 1박' LIMIT 1), 162000, 1,
 '거의 새 제품 수준입니다. 박스/구성품 모두 포함되어 있어요.', 2, NOW() - INTERVAL 11 DAY, NOW() - INTERVAL 7 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '새 제품 장갑 깨끗한 걸로 구해요 (DUMMY-064)' LIMIT 1), 1, (SELECT item_idx FROM item WHERE item_name = '겨울철 야외 러닝용 스마트폰 터치 장갑' LIMIT 1), 182000, 1,
 '거의 새 제품 수준입니다. 박스/구성품 모두 포함되어 있어요.', 3, NOW() - INTERVAL 10 DAY, NOW() - INTERVAL 7 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '초보자용 시합용 공 어떤 거 사야 할까요 (DUMMY-065)' LIMIT 1), 8, (SELECT item_idx FROM item WHERE item_name = '프리미어리그 공인구 - 미개봉 새제품' LIMIT 1), 111000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 3, NOW() - INTERVAL 8 DAY, NOW() - INTERVAL 8 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '초보자용 시합용 공 어떤 거 사야 할까요 (DUMMY-065)' LIMIT 1), 7, (SELECT item_idx FROM item WHERE item_name = '발볼 넓은 축구 스파이크 B' LIMIT 1), 120000, 1,
 '직접 사용해본 제품이라 상태는 자신 있습니다. 합리적인 가격 제안드려요.', 3, NOW() - INTERVAL 8 DAY, NOW() - INTERVAL 8 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '피팅 포함 아이언 세트 구합니다 (DUMMY-066)' LIMIT 1), 1, (SELECT item_idx FROM item WHERE item_name = '중고 아이언 세트 - 사용감 있음' LIMIT 1), 388000, 1,
 '상태 좋은 제품으로 제안드립니다. 직거래/택배 모두 가능합니다.', 1, NOW() + INTERVAL 2 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '피팅 포함 아이언 세트 구합니다 (DUMMY-066)' LIMIT 1), 7, (SELECT item_idx FROM item WHERE item_name = '아이언 세트 - 거의 새 제품' LIMIT 1), 424000, 1,
 '직접 사용해본 제품이라 상태는 자신 있습니다. 합리적인 가격 제안드려요.', 1, NOW() + INTERVAL 3 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '새 제품 손목 보호대 저렴하게 구합니다 (DUMMY-067)' LIMIT 1), 1, (SELECT item_idx FROM item WHERE item_name = '헬스용 손목 스트랩 + 무릎 슬리브' LIMIT 1), 37000, 1,
 '직접 사용해본 제품이라 상태는 자신 있습니다. 합리적인 가격 제안드려요.', 2, NOW() - INTERVAL 20 DAY, NOW() - INTERVAL 17 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '새 제품 손목 보호대 저렴하게 구합니다 (DUMMY-067)' LIMIT 1), 6, (SELECT item_idx FROM item WHERE item_name = '무릎 보호대 세트 - 사용감 적음' LIMIT 1), 40000, 1,
 '거의 새 제품 수준입니다. 박스/구성품 모두 포함되어 있어요.', 3, NOW() - INTERVAL 23 DAY, NOW() - INTERVAL 17 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '운동용 기능성 의류 사이즈 맞는 거 구해요 (DUMMY-068)' LIMIT 1), 7, (SELECT item_idx FROM item WHERE item_name = '기능성 운동 레깅스 (블랙)' LIMIT 1), 117000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 1, NOW() + INTERVAL 2 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '운동용 기능성 의류 사이즈 맞는 거 구해요 (DUMMY-068)' LIMIT 1), 10, (SELECT item_idx FROM item WHERE item_name = '골프웨어 상하의 세트' LIMIT 1), 121000, 1,
 '사용감은 조금 있지만 기능상 문제 없습니다. 좋은 가격에 드릴게요.', 1, NOW() + INTERVAL 2 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '쿠션 좋은 홈트 용품 찾고 있어요 (DUMMY-069)' LIMIT 1), 9, (SELECT item_idx FROM item WHERE item_name = '10km 대회용 러닝화 - 쿠션 좋은 모델' LIMIT 1), 248000, 1,
 '직접 사용해본 제품이라 상태는 자신 있습니다. 합리적인 가격 제안드려요.', 4, NOW() - INTERVAL 13 DAY, NOW() - INTERVAL 11 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '가족용 캠핑 의자 여러 개 구합니다 (DUMMY-070)' LIMIT 1), 6, (SELECT item_idx FROM item WHERE item_name = '스키 풀세트 (구형 장비)' LIMIT 1), 444000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 1, NOW(), NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '입문용 수영복 추천 부탁드려요 (DUMMY-071)' LIMIT 1), 3, (SELECT item_idx FROM item WHERE item_name = '수영 입문 세트 A (수경+수모+수영복)' LIMIT 1), 65000, 1,
 '사용감은 조금 있지만 기능상 문제 없습니다. 좋은 가격에 드릴게요.', 1, NOW() + INTERVAL 5 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '장갑 상태 좋은 거 구합니다 (DUMMY-072)' LIMIT 1), 3, (SELECT item_idx FROM item WHERE item_name = '리조트 숙박권 1박' LIMIT 1), 177000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 5, NOW() - INTERVAL 11 DAY, NOW() - INTERVAL 8 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '초보자용 공인구 어떤 거 사야 할까요 (DUMMY-073)' LIMIT 1), 6, (SELECT item_idx FROM item WHERE item_name = '발볼 넓은 축구 스파이크 B' LIMIT 1), 67000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 2, NOW() - INTERVAL 21 DAY, NOW() - INTERVAL 19 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '초보자용 공인구 어떤 거 사야 할까요 (DUMMY-073)' LIMIT 1), 3, (SELECT item_idx FROM item WHERE item_name = '인조잔디용 축구 스파이크 A' LIMIT 1), 69000, 1,
 '거의 새 제품 수준입니다. 박스/구성품 모두 포함되어 있어요.', 3, NOW() - INTERVAL 20 DAY, NOW() - INTERVAL 19 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '연습용 드라이버 저렴하게 넘겨주실 분 (DUMMY-074)' LIMIT 1), 9, (SELECT item_idx FROM item WHERE item_name = '아이언 세트 - 거의 새 제품' LIMIT 1), 756000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 4, NOW() - INTERVAL 9 DAY, NOW() - INTERVAL 6 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '보호장비 세트 사이즈 맞는 걸로 구합니다 (DUMMY-075)' LIMIT 1), 6, (SELECT item_idx FROM item WHERE item_name = '무릎 보호대 세트 - 사용감 적음' LIMIT 1), 81000, 1,
 '상태 좋은 제품으로 제안드립니다. 직거래/택배 모두 가능합니다.', 1, NOW() - INTERVAL 5 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '계절용 운동복 추천 부탁드립니다 (DUMMY-076)' LIMIT 1), 9, (SELECT item_idx FROM item WHERE item_name = '골프웨어 상하의 세트' LIMIT 1), 48000, 1,
 '직접 사용해본 제품이라 상태는 자신 있습니다. 합리적인 가격 제안드려요.', 4, NOW() - INTERVAL 13 DAY, NOW() - INTERVAL 10 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '계절용 운동복 추천 부탁드립니다 (DUMMY-076)' LIMIT 1), 1, (SELECT item_idx FROM item WHERE item_name = '방수 자켓 - 등산/캠핑용' LIMIT 1), 47000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 4, NOW() - INTERVAL 10 DAY, NOW() - INTERVAL 10 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '홈트용 홈트 용품 구합니다 (DUMMY-077)' LIMIT 1), 8, (SELECT item_idx FROM item WHERE item_name = '10km 대회용 러닝화 - 쿠션 좋은 모델' LIMIT 1), 128000, 1,
 '거의 새 제품 수준입니다. 박스/구성품 모두 포함되어 있어요.', 1, NOW() - INTERVAL 2 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '초보자용 캠핑 의자 추천 부탁드려요 (DUMMY-078)' LIMIT 1), 4, (SELECT item_idx FROM item WHERE item_name = '스키 풀세트 (구형 장비)' LIMIT 1), 674000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 2, NOW() - INTERVAL 9 DAY, NOW() - INTERVAL 9 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '수영 수경 구합니다 (DUMMY-079)' LIMIT 1), 6, (SELECT item_idx FROM item WHERE item_name = '수영 세트 B - 수경 사용감 있음' LIMIT 1), 155000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 3, NOW() - INTERVAL 19 DAY, NOW() - INTERVAL 16 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '백팩 상태 좋은 거 구합니다 (DUMMY-080)' LIMIT 1), 2, (SELECT item_idx FROM item WHERE item_name = '리조트 숙박권 1박' LIMIT 1), 100000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 2, NOW() - INTERVAL 10 DAY, NOW() - INTERVAL 8 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '백팩 상태 좋은 거 구합니다 (DUMMY-080)' LIMIT 1), 6, (SELECT item_idx FROM item WHERE item_name = '대용량 스포츠 백팩 (신발주머니 포함)' LIMIT 1), 103000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 3, NOW() - INTERVAL 8 DAY, NOW() - INTERVAL 8 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '연습용 공용 공인구 상태 좋은 거 구합니다 (DUMMY-081)' LIMIT 1), 2, (SELECT item_idx FROM item WHERE item_name = '인조잔디용 축구 스파이크 A' LIMIT 1), 39000, 1,
 '사용감은 조금 있지만 기능상 문제 없습니다. 좋은 가격에 드릴게요.', 2, NOW() - INTERVAL 19 DAY, NOW() - INTERVAL 15 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '드라이버 중급자용으로 제안 부탁드려요 (DUMMY-082)' LIMIT 1), 3, (SELECT item_idx FROM item WHERE item_name = '연습용 아이언 세트' LIMIT 1), 482000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 1, NOW() + INTERVAL 5 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '드라이버 중급자용으로 제안 부탁드려요 (DUMMY-082)' LIMIT 1), 2, (SELECT item_idx FROM item WHERE item_name = '아이언 세트 - 거의 새 제품' LIMIT 1), 521000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 1, NOW() + INTERVAL 1 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '손목 보호대 사이즈 맞는 걸로 구합니다 (DUMMY-083)' LIMIT 1), 6, (SELECT item_idx FROM item WHERE item_name = '헬스용 손목 스트랩 + 무릎 슬리브' LIMIT 1), 74000, 1,
 '사용감은 조금 있지만 기능상 문제 없습니다. 좋은 가격에 드릴게요.', 1, NOW() + INTERVAL 2 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '손목 보호대 사이즈 맞는 걸로 구합니다 (DUMMY-083)' LIMIT 1), 5, (SELECT item_idx FROM item WHERE item_name = '무릎 보호대 세트 - 사용감 적음' LIMIT 1), 83000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 1, NOW(), NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '계절용 레깅스 추천 부탁드립니다 (DUMMY-084)' LIMIT 1), 3, (SELECT item_idx FROM item WHERE item_name = '드라이핏 라운드 티셔츠 세트' LIMIT 1), 82000, 1,
 '상태 좋은 제품으로 제안드립니다. 직거래/택배 모두 가능합니다.', 4, NOW() - INTERVAL 21 DAY, NOW() - INTERVAL 19 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '입문용 요가 매트 가격대 맞춰 구해요 (DUMMY-085)' LIMIT 1), 6, (SELECT item_idx FROM item WHERE item_name = '가성비 홈트 세트' LIMIT 1), 103000, 1,
 '직접 사용해본 제품이라 상태는 자신 있습니다. 합리적인 가격 제안드려요.', 5, NOW() - INTERVAL 17 DAY, NOW() - INTERVAL 12 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '가족용 캠핑 의자 여러 개 구합니다 (DUMMY-086)' LIMIT 1), 3, (SELECT item_idx FROM item WHERE item_name = '스키 풀세트 (구형 장비)' LIMIT 1), 514000, 1,
 '상태 좋은 제품으로 제안드립니다. 직거래/택배 모두 가능합니다.', 1, NOW() + INTERVAL 1 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '가족용 캠핑 의자 여러 개 구합니다 (DUMMY-086)' LIMIT 1), 10, (SELECT item_idx FROM item WHERE item_name = '스키 풀세트 (구형 장비)' LIMIT 1), 486000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 1, NOW() - INTERVAL 1 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '대회용 수경 상태 좋은 거 구해요 (DUMMY-087)' LIMIT 1), 8, (SELECT item_idx FROM item WHERE item_name = '브랜드 수영 세트 C' LIMIT 1), 88000, 1,
 '거의 새 제품 수준입니다. 박스/구성품 모두 포함되어 있어요.', 1, NOW() - INTERVAL 2 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '대회용 수경 상태 좋은 거 구해요 (DUMMY-087)' LIMIT 1), 4, (SELECT item_idx FROM item WHERE item_name = '수영 세트 B - 수경 사용감 있음' LIMIT 1), 93000, 1,
 '사용감은 조금 있지만 기능상 문제 없습니다. 좋은 가격에 드릴게요.', 1, NOW() - INTERVAL 4 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '스포츠 잡화 상태 좋은 거 구합니다 (DUMMY-088)' LIMIT 1), 9, (SELECT item_idx FROM item WHERE item_name = '겨울철 야외 러닝용 스마트폰 터치 장갑' LIMIT 1), 96000, 1,
 '사용감은 조금 있지만 기능상 문제 없습니다. 좋은 가격에 드릴게요.', 2, NOW() - INTERVAL 11 DAY, NOW() - INTERVAL 8 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '스포츠 잡화 상태 좋은 거 구합니다 (DUMMY-088)' LIMIT 1), 10, (SELECT item_idx FROM item WHERE item_name = '콘서트 티켓 2장' LIMIT 1), 102000, 1,
 '사용감은 조금 있지만 기능상 문제 없습니다. 좋은 가격에 드릴게요.', 3, NOW() - INTERVAL 10 DAY, NOW() - INTERVAL 8 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '시합용 시합용 공 새 제품으로 구해요 (DUMMY-089)' LIMIT 1), 6, (SELECT item_idx FROM item WHERE item_name = '발볼 넓은 축구 스파이크 B' LIMIT 1), 68000, 1,
 '상태 좋은 제품으로 제안드립니다. 직거래/택배 모두 가능합니다.', 1, NOW() + INTERVAL 5 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '피팅 포함 드라이버 구합니다 (DUMMY-090)' LIMIT 1), 2, (SELECT item_idx FROM item WHERE item_name = '아이언 세트 - 거의 새 제품' LIMIT 1), 486000, 1,
 '거의 새 제품 수준입니다. 박스/구성품 모두 포함되어 있어요.', 2, NOW() - INTERVAL 14 DAY, NOW() - INTERVAL 11 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '운동 시 착용할 무릎 보호대 추천받습니다 (DUMMY-091)' LIMIT 1), 2, (SELECT item_idx FROM item WHERE item_name = '축구용 정강이 보호대 (스타킹 포함)' LIMIT 1), 62000, 1,
 '사용감은 조금 있지만 기능상 문제 없습니다. 좋은 가격에 드릴게요.', 3, NOW() - INTERVAL 15 DAY, NOW() - INTERVAL 15 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '가성비 기능성 의류 구성으로 구합니다 (DUMMY-092)' LIMIT 1), 7, (SELECT item_idx FROM item WHERE item_name = '방수 자켓 - 등산/캠핑용' LIMIT 1), 115000, 1,
 '거의 새 제품 수준입니다. 박스/구성품 모두 포함되어 있어요.', 1, NOW() - INTERVAL 1 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '가성비 기능성 의류 구성으로 구합니다 (DUMMY-092)' LIMIT 1), 1, (SELECT item_idx FROM item WHERE item_name = '기능성 운동 레깅스 (블랙)' LIMIT 1), 114000, 1,
 '상태 좋은 제품으로 제안드립니다. 직거래/택배 모두 가능합니다.', 1, NOW(), NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '홈트용 아령 세트 구합니다 (DUMMY-093)' LIMIT 1), 6, (SELECT item_idx FROM item WHERE item_name = '10km 대회용 러닝화 - 쿠션 좋은 모델' LIMIT 1), 114000, 1,
 '필요하시면 추가 사진 더 보내드릴 수 있습니다. 잘 부탁드립니다.', 1, NOW() + INTERVAL 6 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '초보자용 텐트 추천 부탁드려요 (DUMMY-094)' LIMIT 1), 1, (SELECT item_idx FROM item WHERE item_name = '스키 풀세트 (구형 장비)' LIMIT 1), 518000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 1, NOW(), NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '초보자용 텐트 추천 부탁드려요 (DUMMY-094)' LIMIT 1), 5, (SELECT item_idx FROM item WHERE item_name = '스키 풀세트 (구형 장비)' LIMIT 1), 506000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 1, NOW() + INTERVAL 5 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '대회용 수모 세트 상태 좋은 거 구해요 (DUMMY-095)' LIMIT 1), 1, (SELECT item_idx FROM item WHERE item_name = '수영 입문 세트 A (수경+수모+수영복)' LIMIT 1), 75000, 1,
 '사용감은 조금 있지만 기능상 문제 없습니다. 좋은 가격에 드릴게요.', 1, NOW() + INTERVAL 2 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '가성비 백팩 구합니다 (DUMMY-096)' LIMIT 1), 4, (SELECT item_idx FROM item WHERE item_name = '리조트 숙박권 1박' LIMIT 1), 73000, 1,
 '사용감은 조금 있지만 기능상 문제 없습니다. 좋은 가격에 드릴게요.', 1, NOW() + INTERVAL 1 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '가성비 백팩 구합니다 (DUMMY-096)' LIMIT 1), 5, (SELECT item_idx FROM item WHERE item_name = '콘서트 티켓 2장' LIMIT 1), 79000, 1,
 '직접 사용해본 제품이라 상태는 자신 있습니다. 합리적인 가격 제안드려요.', 1, NOW() + INTERVAL 1 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '초보자용 연습용 공 어떤 거 사야 할까요 (DUMMY-097)' LIMIT 1), 8, (SELECT item_idx FROM item WHERE item_name = '프리미어리그 공인구 - 미개봉 새제품' LIMIT 1), 108000, 1,
 '상태 좋은 제품으로 제안드립니다. 직거래/택배 모두 가능합니다.', 4, NOW() - INTERVAL 12 DAY, NOW() - INTERVAL 10 DAY),
((SELECT auction_idx FROM auction WHERE auction_title = '피팅 포함 드라이버 구합니다 (DUMMY-098)' LIMIT 1), 7, (SELECT item_idx FROM item WHERE item_name = '아이언 세트 - 거의 새 제품' LIMIT 1), 459000, 1,
 '거의 새 제품 수준입니다. 박스/구성품 모두 포함되어 있어요.', 1, NOW() - INTERVAL 1 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '손목 보호대 사이즈 맞는 걸로 구합니다 (DUMMY-099)' LIMIT 1), 2, (SELECT item_idx FROM item WHERE item_name = '손목/팔꿈치 보호대 세트' LIMIT 1), 62000, 1,
 '상태 좋은 제품으로 제안드립니다. 직거래/택배 모두 가능합니다.', 1, NOW() + INTERVAL 4 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '손목 보호대 사이즈 맞는 걸로 구합니다 (DUMMY-099)' LIMIT 1), 9, (SELECT item_idx FROM item WHERE item_name = '헬스용 손목 스트랩 + 무릎 슬리브' LIMIT 1), 58000, 1,
 '직접 사용해본 제품이라 상태는 자신 있습니다. 합리적인 가격 제안드려요.', 1, NOW() + INTERVAL 4 DAY, NULL),
((SELECT auction_idx FROM auction WHERE auction_title = '운동용 기능성 의류 사이즈 맞는 거 구해요 (DUMMY-100)' LIMIT 1), 8, (SELECT item_idx FROM item WHERE item_name = '골프웨어 상하의 세트' LIMIT 1), 154000, 1,
 '빠른 배송 가능합니다. 궁금하신 점 있으면 채팅으로 문의 주세요.', 3, NOW() - INTERVAL 17 DAY, NOW() - INTERVAL 16 DAY);